### ISSUE TITLE
RAR v5 is not supported

### ISSUE THREAD

**Issue by dm4tsuo** [mucommander/mucommander#420] opened 2021-02-19 12:21 UTC
I used to navigate with mucommander inside a rar file as any other filesystem. This is something I'm used to do with zip, iso etc. Rar stopped working recently. Any idea why? Latest version checked: 0.9.6 (0.9.7 nightly build too).

**Comment by ahadas** [comment] 2021-02-19 12:33
@dm4tsuo could it be that you're using RAR >= v5.0 now?

**Comment by dm4tsuo** [comment] 2021-02-19 12:52
Sorry. When it comes to windows, I'm a noob. I use WSL so to adapt myself better. ;-) I really don't know which version of rar I'm using. Is it supported natively by windows 10? I didn't install any rar app on windows. I supposed mucommander used an internal rar plugin. Am I worng?

**Comment by ahadas** [comment] 2021-02-19 15:12
Yeah, we use the `junrar` library for this.
How did you create the RAR file?

**Comment by dm4tsuo** [comment] 2021-02-19 17:11
I don't know. As these files are created by my students, I think they use Winrar (probably). I also think they might be using version 5.0 or up. The only software that is opening these files as I wanted is midnight commander (similar to mucommander). I also use servant salamander but it can't open them as a filesystem (these students generate multiple zips inside a rar file...). Thank you for your answers so far and don't bother about this. It's really not that important.

**Comment by ahadas** [comment] 2021-02-19 21:35
Yeah, recent versions of Winrar create RAR 5.0 by default.
They can change it to RAR4 (in the Archive format) option but I guess you can't force them to do that..

As `junrar` [don't intend to support RAR 5.0](https://github.com/junrar/junrar/issues/23#issuecomment-747131993) and I don't see any other Java library that supports it, I'm closing it then.

**Comment by ahadas** [comment] 2022-07-29 19:38
Reopening this one because apparently with [7-Zip-Binding](http://sevenzipjbind.sourceforge.net/) we can support RAR v5 on Windows, Linux and macOS

**Closed** 2022-07-29 20:19 UTC

**Comment by ahadas** [comment] 2022-08-12 20:22
@dm4tsuo I can't reproduce it, I'm able to remove a rar file right after copying its content. Can you please share more information on the version you use - what version (including the 'Build number' that appears in the 'About' dialog), how did you install it..

**Comment by ahadas** [comment] 2022-10-09 17:02
Version 1.1.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.1.0-1)

**Comment by dm4tsuo** [comment] 2022-10-13 07:13
It's working fantastically! Thanks. I'm not sure if alt+4 functionality existed before, but that improved greatly access to bookmarks.
