### ISSUE TITLE
macOS Ventura 13.3: File handling errors due to the changed(?) handling of umlauts

### ISSUE THREAD

**Issue by sebastian-lempert** [mucommander/mucommander#898] opened 2023-03-30 09:39 UTC
### macOS Ventura 13.3: File handling errors due to the changed(?) handling of umlauts

Since I installed macOS Ventura 13.3 I stumbled upon the following error:

Starting from macOS Ventura 13.3 files that were named using muCommander and that contain an German umlaut such as ä, ö or ü in the file name cannot be opened from muCommander, from Finder or from Terminal (open -a Preview [FILENAME]). If you rename the file so that there is no umlaut in the complete path, then the file can be opened.

In contrast to this, it is possible to assign a file name including an umlaut with the Finder and then open this file as usual with muCommander, the Finder or Terminal!

A test with [1] concerning the file name "Überstunden-2022.xlsx" reveals the following differences that occur when naming a file between muCommander and the Finder (see attached screenshots as well):

1. muCommander uses only the following character for the umlaut Ü:
    - Unicode Character 'LATIN CAPITAL LETTER U WITH DIAERESIS' (U+00DC) [2]

2. Finder uses the following two characters for the umlaut Ü:
   - Unicode Character 'LATIN CAPITAL LETTER U' (U+0055) [3]
   - Unicode Character 'COMBINING DIAERESIS' (U+0308) [4]

Can you help me in this regard?

Thank you and best regards, Sebastian

[1] https://qaz.wtf/u/show.cgi
[2] https://www.fileformat.info/info/unicode/char/00DC/index.htm
[3] https://www.fileformat.info/info/unicode/char/0055/index.htm
[4] https://www.fileformat.info/info/unicode/char/0308/index.htm

![Screenshot 2023-03-30 at 11-21-08 Show Unicode Character](https://user-images.githubusercontent.com/18451267/228795020-95f0f32b-4918-4a66-b249-e540bbb49769.png)
![Screenshot 2023-03-30 at 11-21-03 Show Unicode Character](https://user-images.githubusercontent.com/18451267/228795035-ba098aaa-e45b-4e49-8b84-1e65e9a03d0c.png)

**Comment by sebastian-lempert** [comment] 2023-03-30 10:21
Just stumbled upon the following Reddit post that might be helpful in combination with my previous post: https://www.reddit.com/r/MacOS/comments/jhjv41/psa_beware_of_umlauts_and_other_accented/

**Comment by WolfgangFranke** [comment] 2023-03-31 15:37
I can confirm the issue with German "Umlaut" handling on macOS Ventura and muCommander 1.1.0 and 1.2.0 , I verified they do not open by double click or by the Open-Context-menu, without any error message (e.g. PDF, JPG) :
- if the File name was given in muCommander and having German "Umlaut" it will not open;
- if a Folder name was given in muCommander with a German "Umlaut" then all the items in the folder do not open;
- the "File-Drag&Drop" e.g. onto an editor will not open the file in the editor;
- Airdrop does not transfer these files;

It looks like MacOS Ventura changed behavior?
When testing above, I tested files renamed by using muCommander in 2019 and containing German "Umlaut", and they do not open anymore in MacOS Ventura. But other files renamed with Finder in 2019 still work as expected.
Can somebody confirm?

**Comment by WolfgangFranke** [comment] 2023-03-31 15:59
imho muCommander needs an urgent enhancement to handle the new MacOS behavior on German "Umlaut":
-> every time muCommander copies files with a "good Umlaut" , the file name changes to having a "bad Umlaut" of the same character [ä,ö,ü,...].
Looks like a risk to damage existing file names currently.

**Comment by sebastian-lempert** [comment] 2023-03-31 16:10
> I can confirm the issue with German "Umlaut" handling on macOS Ventura and muCommander 1.1.0 and 1.2.0 , I verified they do not open by double click or by the Open-Context-menu, without any error message (e.g. PDF, JPG) :
> 
>     * if the File name was given in muCommander and having German "Umlaut" it will not open;
> 
>     * if a Folder name was given in muCommander with a German "Umlaut" then all the items in the folder do not open;
> 
>     * the "File-Drag&Drop" e.g. onto an editor will not open the file in the editor;
> 
>     * Airdrop does not transfer these files;
> 
> 
> It looks like MacOS Ventura changed behavior? When testing above, I tested files renamed by using muCommander in 2019 and containing German "Umlaut", and they do not open anymore in MacOS Ventura. But other files renamed with Finder in 2019 still work as expected with German "Umlaut". Can somebody confirm?

I can confirm all of the above. Possibly the above problem does not only affect German umlauts, but all languages that use diacritical marks (= accented characters):

- https://en.wikipedia.org/wiki/Diacritic#List_of_diacritics_in_Unicode
- https://web.library.yale.edu/cataloging/music/diacrit

**Comment by pskowronek** [comment] 2023-03-31 16:40
I'm not sure if its gonna add anything meaningful to this discussion, but a month ago I spotted a problem with paths that contain diacritics on Catalina in Terminal - but only for "Mac OS Extended (Journaled)" volume, for APFS it works OK. The problem was that Terminal was unable to autocomplete (TAB) path part where diacritic was present.  For example, create folder ```żółć``` on "Mac OS Extended (Journaled)" filesystem, and try to `cd ż[tab]`  - doesn't work, but if you do `cd z[tab]` then mysteriously `z` is converted to `ż` and it works (the same with `ó`, umlaut etc).  For APFS I don't have such problems.

**Comment by ahadas** [comment] 2023-04-10 14:21
@sebastian-lempert thanks for reporting this and thanks for everyone who has been participating in this thread. unfortunately, I still can't upgrade my macbook to macOS Ventura and it will take some time until I get a new one. I suppose we can address that by [decompressing the filename using Java Normalizer](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/text/Normalizer.html#normalize(java.lang.CharSequence,java.text.Normalizer.Form)) but I'll need your feedback on the proposed fix.
@danielerez do you happen to have macOS Ventura installed on your machine?

**Comment by ahadas** [comment] 2023-04-10 18:52
@Andreas0602 @WolfgangFranke it's a nasty issue indeed and I can publish a new build for macOS once we have a workaround for this issue (that IIRC appears to be an issue in [macOS 13.3](https://discussions.apple.com/thread/254748658) - hopefully Apple will also fix that and not rely on the proposed workaround in that thread).

**Comment by ahadas** [comment] 2023-04-10 19:37
ok, I've uploaded a version that might fix this [here](https://github.com/mucommander/mucommander/releases/download/nightly/mucommander-1.3.0-snapshot.tgz) - @Andreas0602 could you please give it a try?

**Comment by ahadas** [comment] 2023-04-10 20:02
@Andreas0602 which flow did you test?

**Comment by ahadas** [comment] 2023-04-10 20:22
I see, yeah - it seems to be normalized again by Java later on. IIUC [the path should have been normalized with NFD with Java < 20](https://bugs.openjdk.org/browse/JDK-8297159).. maybe it is worth checking with Java >= 20

**Comment by ahadas** [comment] 2023-04-11 11:35
@Andreas0602 this means it's most probably the same with Openjdk but still I'd give Openjdk a try, I don't know if the changes I see in Openjdk are included in Oracle's distribution

**Comment by ahadas** [comment] 2023-04-11 13:22
@Andreas0602 I see, thanks for checking. So it really seems we cannot do much then. Could you try to compile and run the following class with Java 20 and confirm that Finder cannot open both files that are created on the same directory and start with `Überstunden-2022`:
```java
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.text.Normalizer;

public class Form {

    public static void main(String[] args) throws IOException {
        var nfdStr = "Überstunden-2022-nfd.txt";
        var nfd = Normalizer.normalize(nfdStr, Normalizer.Form.NFD);
        var nfcStr = "Überstunden-2022-nfc.txt";
        System.out.println("nfd =\t" + nfd);
        System.out.println("nfd.length() =\t" + nfd.length());
        var nfc = Normalizer.normalize(nfcStr, Normalizer.Form.NFC);
        System.out.println("nfc =\t" + nfc);
        System.out.println("nfc.length() =\t" + nfc.length());
        File nfdFile = new File(nfd);
        File nfcFile = new File(nfc);
        System.out.println("nfdFile: \t" + nfdFile.getPath().length());
        System.out.println("nfsFile: \t" + nfcFile.getPath().length());
        nfdFile.createNewFile();
        Files.writeString(nfdFile.toPath(), "content-nfd");
        nfcFile.createNewFile();
        Files.writeString(nfcFile.toPath(), "content-nfc");
    }

}
```
It can be compiled and run by executing: `javac Form.java; java Form`

**Comment by ahadas** [comment] 2023-04-11 16:09
@Andreas0602 , great! I've pushed [another commit to this branch to fix copy/move](https://github.com/ahadas/mucommander/commit/1881dbc92899ad0b53cfffb28b5a769fdc74b404), can you please give it a try?

**Comment by ahadas** [comment] 2023-04-11 21:31
@Andreas0602 could you kindly test the latest state of the `bug_898` branch before I merge #900 ? by repeating the steps you've wrote in [the previous comment](https://github.com/mucommander/mucommander/issues/898#issuecomment-1502245221), you could then create a dmg that is bundled with Java 20 and test it instead of running `gradlew run`

**Comment by ahadas** [comment] 2023-04-12 17:54
The fix was merged and a [new build was published](https://github.com/mucommander/mucommander/releases/download/1.2.0-1/mucommander-1.2.0-2.dmg) - the website was updated and the previous 1.2.0 build will be dropped [once Homebrew is updated](https://github.com/Homebrew/homebrew-cask/pull/144970). Thanks everyone for reporting and helping in making this fix!

**Closed by ahadas** 2023-04-12 17:54 UTC

**Comment by WolfgangFranke** [comment] 2023-04-12 18:43
It works very well , thank you @ahadas @Andreas0602 for the very quick fix !

**Comment by sebastian-lempert** [comment] 2023-04-13 10:18
@ahadas and @Andreas0602 thank you for all the efforts so far. I did test the new version [muCommander-1.2.0-2.dmg](https://github.com/mucommander/mucommander/releases/download/1.2.0-1/muCommander-1.2.0-2.dmg) with macOS 13.3.1. Unfortunately it doesn't look like the bug is completely fixed. Here is what I tried.

## Renaming a file

I have been trying to repeatedly renaming and opening a file that contains one or more umlauts / diacritical marks (= accented characters) in the file name. Sometimes it works, sometimes not. For example I did the following tests.

### Test 1

1. Within muCommander rename the file from N**ue**rnberg-F**ue**rth.png to N**ü**rnberg-F**ü**rth.png.
2. In muCommander open the file with Preview using right arrow key or Shift + Return.
3. Close Preview.
4. Rename back to N**ue**rnberg-F**ue**rth.png.
5. Open file in Preview.
6. Close Preview.
7. Rename back to N**ü**rnberg-F**ü**rth.png.
8. Open file in Preview.
9. Close Preview.
10. etc.

### Test 2

Similar to Test 1 but this time only using one umlaut / diacritical mark:

1. Within muCommander rename the file from N**ue**rnberg-F**ue**rth.png to N**ü**rnberg-F**ue**rth.png.
2. In muCommander open the file with Preview using right arrow key or Shift + Return.
3. Close Preview.
4. Rename back to N**ue**rnberg-F**ue**rth.png.
5. Open file in Preview.
6. Close Preview.
7. Rename back to N**ü**rnberg-F**ue**rth.png.
8. Open file in Preview.
9. Close Preview.
10. etc.

### Test 3

Similar to Test 1 and 2 but this time using 2 or 3 umlauts / diacritical marks:

1. Within muCommander rename the file from N**ue**rnberg-F**ue**rth.png to N**ü**rnberg-F**ü**rth.png.
2. In muCommander open the file with Preview using right arrow key or Shift + Return.
3. Close Preview.
4. Rename file from N**ü**rnberg-F**ü**rth.png to N**ü**rnberg-F**ü**rth-**ü**.png.
5. Open file in Preview.
6. Close Preview.
7. Rename file to N**ü**rnberg-F**ü**rth.png.
8. Open file in Preview.
9. Close Preview. etc.

Whenever renaming a file resulted in a file that couldn't be opened anymore it was necessary to rename the file again and make sure that all umlauts / diacritical marks are removed in order to be able to open the file again.

## Moving a file

Furthermore I tried to repeatedly move a file between two different folders and to open the file in between.

### Test 4

1. Create to folders A and B and make sure that the paths to folders A and B doesn't contain a single umlaut / diacritical mark.
2. Create a file Nürnberg-Fürth.png with Finder in folder A and make sure, that this file can be opened in Preview without problems.
3. In muCommander move the file to folder B.
4. In muCommander open the file with Preview using right arrow key or Shift + Return.
5. Close Preview.
6. In muCommander move the file to back to folder A.
7. Open file in Preview.
8. Close Preview.
9. Move file back to folder B.
10. Open file in Preview.
11. Close Preview.
12. etc.

I tried this several times. Here always(!) in step 7 it wasn't possible to open the file anymore. Whenever moving a file resulted in a file that couldn't be opened anymore it was necessary to rename the file again and make sure that all umlauts / diacritical marks are removed in order to be able to open the file again.

**Comment by ahadas** [comment] 2023-04-13 11:00
> I did test the new version [muCommander-1.2.0-2.dmg](https://github.com/mucommander/mucommander/releases/download/1.2.0-1/muCommander-1.2.0-2.dmg) with macOS 13.3.1. Unfortunately it doesn't look like the bug is completely fixed. 

yeah, I wouldn't consider this a bug-fix though but rather a workaround for an issue in macOS 13.3. I believe Apple would try to fix that at some point so unless there is an easy way to improve the workaround in 1.2.0-2 and considering that a common use should work now, I'd wait to see how it goes on the macOS side before putting more effort on that. but thanks for reporting

**Comment by ahadas** [comment] 2023-04-13 11:39
sure, it only affect some applications - it depends on how they interact with the operating system. I saw other project that closed an issue like this, saying it's an issue in macOS but as it affects basic functionality in muCommander, the implemented workaround was worth the effort in my opinion.
don't get me wrong, I'm not against improving it - in my view the effort that it would require to address those flows won't be cost-effective but I would appreciate contribution(s) for improving it

**Comment by WolfgangFranke** [comment] 2023-04-13 20:00
@ahadas @Andreas0602 I can confirm the issue @sebastian-lempert reported when "moving files/folders" around,  and I reproduced it, in a very special condition only. 
From outside view, it feels like some weird "caching mechanism of file names" is still forcing to write "bad Umlaut characters" in file names when F6-Moving files/folders. 

Issue reproduction: 
Create two folders 'Folder-A' and 'Folder-B' on the SAME partition (APFS, Ventura 13.3.1),
and have a file with a good file name "Nürnberg.jpg" ready in 'Folder-A' , then:
- F6-Move the file from 'Folder-A' into 'Folder-B'  :  still ok
- F6-Move the file back into 'Folder-A'  :  broken (also moving a folder with Umlaut breaks)

But, it does work fine under 2 other conditions:
- if you Exit and Start the muCommander app between each F6-Move (feels like the cache is not persisted)
- if the two folders are created on different partitions (feels like the name caching only works on same partition)

Further playing that game led to the conclusion:
- doing the F6-Move back and forth with renaming "Nürnberg.jpg" to "Nürnberg-1.jpg" and then "Nürnberg-2.jpg" so on, that works fine,
- but the moment of F6-Move with renaming it back to "Nürnberg.jpg" will break the file name.

So, I assume something in the system remembers that the filename was already used in that folder before, and then writes a file name with "bad Umlaut", even after 10 renamings.

fyi: this issue seems to be only in "F6-Move". I tested moving it by "copy&delete" instead, as well as many F5-Copy, and all "Copy" seems to works fine.

**Comment by WolfgangFranke** [comment] 2023-04-14 01:34
(2) removing the USB-Stick (ExFAT) does not help, so the file name cache is not cleared by that
- F6-Move the file from 'Folder-A' into 'Folder-B' : still ok
- remove and re-insert the USB-Stick (ExFAT)
- F6-Move the file back into 'Folder-A' : broken

**Comment by WolfgangFranke** [comment] 2023-04-14 01:58
(3) test if the cache stores a file system inode or the real file name  : **it's the file name**.
- take 2 screenshots , that usually generates 2 PNG files on the desktop,
- create a test folder on the desktop,
- use muCommander to F6-Move and rename the 1st screenshot into "ä-test.png" (moved file will be ok)
- delete the file from the test folder
- use muCommander to F6-Move and rename the 2nd screenshot into "ä-test.png" (same name as before - broken now)

How does the system remembers there was a file with that name before in that folder?
Why is only F6-Move triggering the cache mechanism and forces to write a bad filename, and not F5-Copy? (I did try the above with F5-Copy and it does work fine.)

**Comment by sebastian-lempert** [comment] 2023-04-14 09:13
Thank @WolfgangFranke for all your tests and for pointing out that this might be a caching issue in combination with F6-Move. I would like to add that renaming files might also be related to this issue since renaming is done with Shift+F6 and might use the same functionality as moving a file since from an abstract point of view renaming a file is the same as moving a file within the same directory while changing its name.

**Comment by WolfgangFranke** [comment] 2023-04-23 19:16
Thank you @Andreas0602 for the script, will be very helpful as the change in Ventura broke some more important Apps than this.

I'm glad @ahadas and you quickly changed the Java version under the muCommander, so it works again for many end users like me.  I would wish other impacted Apps would get the necessary changes that quickly...

**Comment by WolfgangFranke** [comment] 2023-04-23 19:18
@ahadas would you have some time left for an initial thought why muCommander remembers that a filename was already used an folder, and with a F6-Move to this folder then it suddenly writes a file name with "bad Umlaut", even after many renamings in between (issue is only in "F6-Move"). 

Pls see my debugging above, if it makes sense I can open a new Git issue for that.

**Comment by sebastian-lempert** [comment] 2023-05-10 07:03
Beside reporting this issue here I was reporting the same issue to Apple using the [Apple Feedback Assistant](https://feedbackassistant.apple.com/). I just received the following answer from Apple:

> Hi Sebastian,
> 
> There are changes in the latest update, build 22F62, that may have resolved this issue.
> You can see the software build your device is running and check for the latest update by clicking on the Apple logo in the upper left hand corner > About This Mac. If the build is not visible, click on the macOS version, e.g. 10.15.x, to reveal it.
> 
> Has this issue been resolved after installing the latest update?
> 
> Feedback ID FB12085030, macOS Ventura 13.3: Handling German umlauts 1. when opening files whose file names contain an umlaut and 2. when searching for text in a PDF file that contains an umlaut
> 
> Do not reply to this email.  Please login to Feedback Assistant or the seed portal to let us know if the problem is fixed for you.

My MacBook is a work computer, which is administered by my employer and on which macOS Ventura 13.3.1 (a) (22E772610a) is currently installed. Unfortunately, I can only install a macOS update when it has been released by my employer. The above mentioned [version 22F62 seems to be a beta version,](https://betawiki.net/wiki/MacOS_Ventura_build_22F62) which was apparently only released for Apple developers and public beta testers. Is there anyone here who can test the above beta version and check if the problems described here have been fixed?

**Comment by sebastian-lempert** [comment] 2023-05-19 07:08
> Beside reporting this issue here I was reporting the same issue to Apple using the [Apple Feedback Assistant](https://feedbackassistant.apple.com/). I just received the following answer from Apple:
> 
> > Hi Sebastian,
> > There are changes in the latest update, build 22F62, that may have resolved this issue.
> > You can see the software build your device is running and check for the latest update by clicking on the Apple logo in the upper left hand corner > About This Mac. If the build is not visible, click on the macOS version, e.g. 10.15.x, to reveal it.
> > Has this issue been resolved after installing the latest update?
> > Feedback ID FB12085030, macOS Ventura 13.3: Handling German umlauts 1. when opening files whose file names contain an umlaut and 2. when searching for text in a PDF file that contains an umlaut
> > Do not reply to this email.  Please login to Feedback Assistant or the seed portal to let us know if the problem is fixed for you.
> 
> My MacBook is a work computer, which is administered by my employer and on which macOS Ventura 13.3.1 (a) (22E772610a) is currently installed. Unfortunately, I can only install a macOS update when it has been released by my employer. The above mentioned [version 22F62 seems to be a beta version,](https://betawiki.net/wiki/MacOS_Ventura_build_22F62) which was apparently only released for Apple developers and public beta testers. Is there anyone here who can test the above beta version and check if the problems described here have been fixed?

I just updated to macOS Ventura 13.4 (22F66) and can confirm that the issue with handling German umlauts when opening files whose file names contain an umlaut is gone. The other issue with searching for text in a PDF file that contains an umlaut is apparently still present, but does not affect muCommander, but macOS itself.

**Comment by ahadas** [comment] 2023-05-19 21:23
great!
