### ISSUE TITLE
MacOS - cant open - says its damaged file

### ISSUE THREAD

**Issue by marisphg** [mucommander/mucommander#116] opened 2017-07-14 13:13 UTC
Downloaded new version.
Copied it in Applications folder, replacing old version.
Tried to open and - says its damaged.

<img width="1042" alt="screenshot 2017-07-14 16 10 50" src="https://user-images.githubusercontent.com/30178291/28213586-65985fec-68af-11e7-8e76-25fccbd91aa4.png">

**Comment by ahadas** [comment] 2017-07-14 15:08
Duplicate of #64, please look at possible solutions described there.
Feel free to reopen if it is a different issue.

**Closed by ahadas** 2017-07-14 15:08 UTC
