### ISSUE TITLE
Settings for columns not saved

### ISSUE THREAD

**Issue by bambi24x** [mucommander/mucommander#480] opened 2021-05-28 14:13 UTC
Everytime I edit the columns to don't show "permissions" muCommander doesn't remember it when I close and restart the app.

Thanks for your help!

**Comment by ahadas** [comment] 2021-05-29 21:52
@bambi24x the visibility of the columns is actually persisted and loaded from the `snapshot.xml` file on startup - can you please share that file (which is located in the same folder as the [customization files](https://github.com/mucommander/mucommander/wiki/Preference-Files)) after setting not to show the `permissions` column and closing the application? there should be a tag `<snapshot><windows><window-0><panels><left/right><file_table><permissions><show>` that should be set to `false`

**Comment by bambi24x** [comment] 2021-05-30 18:03
I've found 2 entries. One for left and one for right.

<permissions>
                            <show>false</show>
                            <width>37</width>
                            <position>4</position>
                        </permissions>


<permissions>
                            <show>false</show>
                            <width>36</width>
                            <position>4</position>
                        </permissions>

**Comment by ahadas** [comment] 2021-05-30 21:16
Interesting, and yet the permissions column is set? I can't reproduce it.. what version of muCommander do you use?

**Comment by bambi24x** [comment] 2021-06-03 08:04
Yes. Version 0.9.7-1.

**Comment by ahadas** [comment] 2021-06-03 21:45
@bambi24x can you please check [this video](https://www.youtube.com/watch?v=Rw4zEXl2EUQ) in which I hide the permissions column from the left panel and tell what you do differently?

**Comment by ahadas** [comment] 2021-06-03 21:48
Did you set custom folders in the preferences->folder dialog maybe?

**Closed** 2021-06-04 15:52 UTC

**Comment by bambi24x** [comment] 2021-06-06 17:21
> @bambi24x can you please check [this video](https://www.youtube.com/watch?v=Rw4zEXl2EUQ) in which I hide the permissions column from the left panel and tell what you do differently?

Nothing different.

**Comment by bambi24x** [comment] 2021-06-06 17:22
> Did you set custom folders in the preferences->folder dialog maybe?

Yes.

**Comment by ahadas** [comment] 2022-04-22 16:10
Version 1.0.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.0.0-1)
