### ISSUE TITLE
0.9.1 on High Sierra 10.13.1

### ISSUE THREAD

**Issue by Dan-Essin** [mucommander/mucommander#135] opened 2017-11-22 03:05 UTC
App is damaged, can't be opened and should be moved to the trash.

![2017-11-21_18-58-27](https://user-images.githubusercontent.com/1776053/33108027-da1989d6-ceee-11e7-83bb-d7f629380698.jpg)

**Comment by ankitshah009** [comment] 2017-11-22 03:11
The app works as expected. I had downloaded 0.9.2 from the website. Link - http://www.mucommander.com/index.html#download

**Comment by Meilenstein** [comment] 2018-01-08 20:23
Same error message on 10.13.2 with 0.9.2 and 0.9.1
Any ideas?

**Comment by ekuester** [comment] 2018-01-20 22:18
The culprit IMHO is the firewall protection of macOS. Sometimes it helps to right click on the application icon and left click in the little window on Open. I have found that the best way to avoid this problem is to compile the program by yourself, which is indeed simpler as one should believe ...

**Comment by Meilenstein** [comment] 2018-03-26 14:48
The following steps solved the problem for me and I can start mucommander again:

The solution to the problem in macOSX is to be found in security & privacy (gatekeeper)
There are 3 options:
- App Store
- App store and identified developers
- Anywhere

The option "Anywhere" is hidden by default in Gatekeeper for macOS 10.13.3
To enable it, I followed this instruction:
http://osxdaily.com/2016/09/27/allow-apps-from-anywhere-macos-gatekeeper/

**Comment by ekuester** [comment] 2018-03-26 16:56
@Meilenstein You can solve the problem this way, of course, but hold in mind, that then your computer is open for every malware program. Switch Gatekeeper as soon as possible back again ...

**Comment by ahadas** [comment] 2020-06-19 10:42
Duplicate of #64

**Closed by ahadas** 2020-06-19 10:43 UTC
