### ISSUE TITLE
Unable to install 1.3.0+ ver on Mac by .dmg

### ISSUE THREAD

**Issue by SouppuoS** [mucommander/mucommander#1007] opened 2023-07-18 16:11 UTC
Hi,
I update mucommander from 1.2.0 to 1.3.0.
Steps like, download .dmg file from github, check md5, double click, agree licence and finally drag the icon.
Then I launch it. A message pops up, "the application is broken, you should drag it into trash".

I tried 1.3.0 and nightly version, both are broken.
I also tried 1.2.0, it is ok.

I'm using mac m1, Ventura 13.4.1.
Need help please.

**Comment by ahadas** [comment] 2023-07-18 17:49
Duplicate of #999

**Closed by ahadas** 2023-07-18 17:49 UTC
