### ISSUE TITLE
Mac dmg 1 3 0 1 seems to be damaged[Bug] 

### ISSUE THREAD

**Issue by Filou53** [mucommander/mucommander#1050] opened 2023-09-10 13:46 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues (including the closed ones)

### Description

When I want to install the last Mac dmg (version 1 3 0 1), I just obtain the message:

_« muCommander.app » est endommagé et ne peut pas être ouvert. 
Vous devriez placer cet élément dans la Corbeille.
Firefox a téléchargé ce fichier aujourd'hui à14:48._

I retryed the same operation with the same result 🙁
[Capture 2023-09-10 à 15.34.21.pdf](https://github.com/mucommander/mucommander/files/12568297/Capture.2023-09-10.a.15.34.21.pdf)

### Steps to reproduce

go to the dmg file
clic on it
copy the file in /Applications
double-clic on it

and boum !

### Expected behavior

the application should appear and it does'nt

### Actual behavior

please see my capture
[Capture 2023-09-10 à 15.34.21.pdf](https://github.com/mucommander/mucommander/files/12568303/Capture.2023-09-10.a.15.34.21.pdf)

### muCommander version

1 3 0 1

### Java version

I have no access to MuCommander / About ...

### Operating System type and version

Mac OS Ventura 13 5 2

**Comment by ahadas** [comment] 2023-09-10 13:59
Duplicate of #999

**Closed by ahadas** 2023-09-10 13:59 UTC
Labels: bug
