### ISSUE TITLE
muCommander 0.9.2 start problem (Mac OS)

### ISSUE THREAD

**Issue by yurkus** [mucommander/mucommander#105] opened 2017-06-14 11:57 UTC
Unable to start muCommander. Seems like JavaAppLauncher problem. Able to start with .jar

**Comment by alexey-lysiuk** [comment] 2017-06-14 12:41
What's the error? I guess it's a potential duplicate of #64 and related reports.

**Closed** 2017-06-14 12:51 UTC
