### ISSUE TITLE
[Enhancement] When selecting a file in the software and pressing "Cmd + C", I only obtain the file path instead of copying the actual file.

### ISSUE THREAD

**Issue by xx299x** [mucommander/mucommander#982] opened 2023-06-15 08:32 UTC
### Description

<img width="808" alt="image" src="https://github.com/mucommander/mucommander/assets/23482348/00b99b5d-4aaf-4bde-9a94-7177e311acbd">
The behavior is shown in the figure.
<img width="901" alt="image" src="https://github.com/mucommander/mucommander/assets/23482348/8fde8335-a89d-4e7f-9d9e-9f246155aca9">
Pressing "Cmd + C" in Finder will copy the file to the clipboard, as shown in the image above

**Comment by xx299x** [comment] 2023-06-16 14:38
> > rather than binary file
> > Currently CMD+C copies the path to clipboard.....
> > What's that window on top?
> 
> Could you elaborate more? Pls update description with what you experience now and what would you like to have.

I have restated my question. Thank you for the response.

**Comment by ahadas** [comment] 2023-06-17 14:27
@xx299x  I'm at a conference with a machine I can't test this on at the moment but within mucommander we are supposedly calling `CopyFilesToClipboard` when META+C is called and call `PasteClipboardFiles` when pasting - do I get it correctly that you paste the content outside of mucommander?

**Comment by xx299x** [comment] 2023-06-17 15:28
> 

@ahadas 
<img width="275" alt="image" src="https://github.com/mucommander/mucommander/assets/23482348/decf8406-5e65-44aa-9391-0ccb46936d89">
Yeah, I can't paste it into other apps like Finder after I copy it from this software.

**Comment by ahadas** [comment] 2023-08-06 05:20
Duplicate of #239

**Closed by ahadas** 2023-08-06 05:20 UTC
Labels: enhancement
