### ISSUE TITLE
Copying files on MacOS X hangs application

### ISSUE THREAD

**Issue by januks** [mucommander/mucommander#180] opened 2018-11-23 08:15 UTC
Updated to 0.9.3 when copying file/s it stalls on progress and nothing happens.

**Comment by twhimes** [comment] 2018-12-03 04:46
Same problem.  Running a 2017 Macbook Pro, 1TB SSD drive, Encrypted. OS-X Sierra v10.12.6.
Copy Opens, then just never starts.

**Comment by ahadas** [comment] 2018-12-03 09:06
@januks @twhimes  Thanks for reporting this. Could you please provide more information like does it happen with all files or with a specific type of source/destination folders? Can you check for errors in the log?

**Comment by twhimes** [comment] 2018-12-03 15:49
Arik,

This is the Debug Log from the “Run Command” window.  Attempting to do a “find” command and then again
doing a “pwd” command.  All shell commands give the same error response.

Let me know if there is any other logs I can look at, and where they are located.

Thanks for all your help.

Terry


[2018-12-03 07:41:34.935] FINEST RecordReaper.java#run,53 RecordReaper(LMC-060644.local.).run() JmDNS reaping cache
[2018-12-03 07:41:39.172] FINE StatusBar.java#updateVolumeInfo,316 Cache hit!
[2018-12-03 07:41:40.372] FINEST FocusDialog.java#windowActivated,229 requesting focus on initial focus component
[2018-12-03 07:41:40.396] FINEST FocusDialog.java#windowActivated,237 requestFocusInWindow failed, calling requestFocus
[2018-12-03 07:41:40.399] FINE FocusRequester.java#run,103 focus requested on com.mucommander.ui.dialog.shell.ShellComboBox
[2018-12-03 07:41:43.761] FINE Shell.java#execute,123 Executing find . -iname "*jpl*.docx"
[2018-12-03 07:41:43.771] FINE AbstractProcess.java#startMonitoring,93 Starting process merged output monitor...
[2018-12-03 07:41:43.783] FINE ProcessOutputMonitor.java#run,116 Process output stream emptied, closing
[2018-12-03 07:41:43.784] FINE RunDialog.java#processDied,237 process exit, return value= 1
[2018-12-03 07:41:44.941] FINEST RecordReaper.java#run,53 RecordReaper(LMC-060644.local.).run() JmDNS reaping cache
[2018-12-03 07:41:54.902] FINE Shell.java#execute,123 Executing pwd
[2018-12-03 07:41:54.902] FINE ShellHistoryManager.java#add,153 Adding  pwd to shell history.
[2018-12-03 07:41:54.911] FINE AbstractProcess.java#startMonitoring,93 Starting process merged output monitor...
[2018-12-03 07:41:54.924] FINE ProcessOutputMonitor.java#run,116 Process output stream emptied, closing
[2018-12-03 07:41:54.925] FINE RunDialog.java#processDied,237 process exit, return value= 1
[2018-12-03 07:41:54.944] FINEST RecordReaper.java#run,53 RecordReaper(LMC-060644.local.).run() JmDNS reaping cache
[2018-12-03 07:42:04.947] FINEST RecordReaper.java#run,53 RecordReaper(LMC-060644.local.).run() JmDNS reaping cache

"A Purple Heart proves you were smart enough to hatch a plan,
 stupid enough to try it and lucky enough to survive!"

Terry W. Himes
JPL Jet Propulsion Laboratory
Dawn Spacecraft Team
Juno Systems & Software Team
TGO Sequence Lead
Phone: (818) 393-6261
Cell:     (818) 653-8213
thimes@jpl.nasa.gov<mailto:thimes@jpl.nasa.gov>
🇺🇸

**Comment by januks** [comment] 2018-12-03 15:58
Where do You get logs from?

**Comment by twhimes** [comment] 2018-12-03 15:59
Debug console.  Set to “Finest”.

Is there another log file somewhere?

"A Purple Heart proves you were smart enough to hatch a plan,
 stupid enough to try it and lucky enough to survive!"

Terry W. Himes
JPL Jet Propulsion Laboratory
Dawn Spacecraft Team
Juno Systems & Software Team
TGO Sequence Lead
Phone: (818) 393-6261
Cell:     (818) 653-8213
thimes@jpl.nasa.gov<mailto:thimes@jpl.nasa.gov>
🇺🇸

**Comment by ahadas** [comment] 2018-12-05 23:21
@twhimes , Thanks but these logs seems to be related to #178 , right? so let' discuss them there.
I would still be interested in relevant logs for this issue since I can't reproduce it.

**Comment by ahadas** [comment] 2022-07-01 04:28
Insufficient information, couldn't reproduce

**Closed by ahadas** 2022-07-01 04:28 UTC
