### ISSUE TITLE
Open with is grayed

### ISSUE THREAD

**Issue by Phils955** [mucommander/mucommander#803] opened 2022-12-13 07:33 UTC
Hello, 
I like mucommander a lot, but I have this problem, when I right click on a file OpenWith is grayed.
I don't have this with other file management tools.
I am running
version 1.1.0 on MacOS
Many thanks for your help

**Comment by Phils955** [comment] 2022-12-15 22:46
Closed by mistake, sorry

**Comment by ahadas** [comment] 2022-12-16 07:01
Duplicate of #759

**Closed by ahadas** 2022-12-16 07:01 UTC
