### ISSUE TITLE
muCommander doesn't start on macosx with java 8

### ISSUE THREAD

**Issue by jkost** [mucommander/mucommander#54] opened 2016-11-17 20:14 UTC
Hallo,

I recently downloaded version 0.9.1 but when I click the icon to start it I get the following error.

`java.lang.IllegalAccessError: class com.jidesoft.plaf.LookAndFeelFactory (in unnamed module @0x4ef37659) cannot access class com.sun.java.swing.plaf.windows.WindowsLookAndFeel (in module java.desktop) because module java.desktop does not export com.sun.java.swing.plaf.windows to unnamed module @0x4ef37659
 at com.jidesoft.plaf.LookAndFeelFactory.installJideExtension(LookAndFeelFactory.java:848)
 at com.jidesoft.plaf.LookAndFeelFactory.installJideExtension(LookAndFeelFactory.java:633)
 at com.jidesoft.plaf.LookAndFeelFactory.installJideExtension(LookAndFeelFactory.java:598)
 at com.jidesoft.swing.StyledLabel.updateUI(StyledLabel.java:103)
 at javax.swing.JLabel.<init>(java.desktop@9-ea/JLabel.java:162)
 at javax.swing.JLabel.<init>(java.desktop@9-ea/JLabel.java:233)
 at com.jidesoft.swing.StyledLabel.<init>(StyledLabel.java:66)
 at com.jidesoft.swing.StyledLabelBuilder.createStyledLabel(StyledLabelBuilder.java:252)
 at com.mucommander.ui.main.table.FileTable$2.createRefreshNonExistingLocationLabel(FileTable.java:256)
 at com.mucommander.ui.main.table.FileTable$2.<init>(FileTable.java:252)
 at com.mucommander.ui.main.table.FileTable.createOverlayableTable(FileTable.java:248)
 at com.mucommander.ui.main.table.FileTable.<init>(FileTable.java:238)
 at com.mucommander.ui.main.FolderPanel.<init>(FolderPanel.java:169)
 at com.mucommander.ui.main.MainFrame.<init>(MainFrame.java:286)
 at com.mucommander.ui.main.frame.DefaultMainFramesBuilder.createMainFrame(DefaultMainFramesBuilder.java:112)
 at com.mucommander.ui.main.frame.DefaultMainFramesBuilder.build(DefaultMainFramesBuilder.java:83)
 at com.mucommander.ui.main.WindowManager.createNewMainFrame(WindowManager.java:166)
 at com.mucommander.muCommander.main(muCommander.java:582)
`
I had found a solution, which was to add a jvm option inside `Info.plist`:
`
<key>JVMOptions</key>
    <array>
      <string>-Djava.system.class.loader=com.mucommander.commons.file.AbstractFileClassLoader</string>
      <string>-Dcom.apple.smallTabs=true</string>
      <string>-Dcom.apple.hwaccel=true</string>
      <string>-Dapple.laf.useScreenMenuBar=true</string>
      <string>-Dfile.encoding=UTF-8</string>
     <string>-XaddExports:java.desktop/com.apple.eawt=ALL-UNNAMED</string>
    </array>
`
but since I had to restore due to an error of my macbook, the modification is gone and I can't remember any more.

I run OSX 10.9.5 with JDK 1.8.0_112.

Running it from the command line with `java -jar mucommander.jar` runs without any issue.

**Comment by twwwt** [comment] 2016-11-26 00:47
Same as #47

**Comment by ahadas** [comment] 2016-12-11 11:30
Duplicate of #47

**Closed by ahadas** 2016-12-11 11:30 UTC
