### ISSUE TITLE
1.4.x MacOS bundled runtime is for MacOS 11

### ISSUE THREAD

**Issue by MeTalOneOEight** [mucommander/mucommander#1246] opened 2024-07-24 07:23 UTC
The included runtime in 1.4.x is build for MacOS 11, this results in the app not working on older MacOS versions.
Is this an intended behaviour?
If yes, add some info to the release notes (I found it under Known Issues after posting here, but this should be a Minimum System Requirement) and update the required minimum system in the app bundle LSMinimumSystemVersion to MacOS 11.
If not, use a runtime which works with older MacOS systems too.

As a workaround copying the runtime over from 1.3.0 to 1.4.x or using a current release from Adoptium seems to work, if anyone doesn't want to wait for a fix.

**Comment by MacTerrassa** [comment] 2024-08-15 13:18
I understand that with the passage of time, it is necessary to change the requirements of any program, and even more so if it is based on other libraries, as is the case with the use of Java.

And furthermore, all code is written to work from a certain system (or hardware) version. This should be indicated so that users know what to expect. Whether or not they can get the program to work correctly.

Furthermore, I do not see any indication on their website or help where these requirements appear. I only see that once the dmg is mounted on the desktop, you can get information about the program and here it indicates system 10.11 El Capitan. But as the previous message says, it turns out that the built-in version of Java, which does not appear anywhere, only works from system 11 Big Sur. This should be indicated both on the download page itself, as well as in the help, and possibly also in the release notes, especially when changes occur in these requirements to avoid saturating your support with issues that you take for granted. Not everyone can use the latest system or hardware. And many times, it is by using these obsolete systems that many of us begin to look at their programs, thinking that they work and if they don't, or indicate anything, we understand that the program is simply poorly developed and therefore useless. And that may not be the case, if the problem is simply unstated minimum requirements.

**Comment by ahadas** [comment] 2024-08-17 20:49
@MacTerrassa thanks for filing this. it can also explain the issue in #1163.
let me give some background:
1. few years ago, muCommander was not shipped with bundled Java, and we kept compatibility with a relatively old version of Java (8). so it didn't make much sense to say on which muCommander is supported (since we didn't really test the app on older versions of macOS) but to say on which **versions of Java**, the application is supported and users needed to make sure a supported version of Java runs on their machine.
2. later, we've changed the minimal version of Java that is supported to Java 11 and we followed the recommendation to bundle Java with the application. that didn't change things much as Java 8 was out of support and the bundled Java ran on most of the machines users have out there.
3. In muCommander 1.4.0, in order to solve #1029 we started bundling a custom version of Java that [is built by us](https://github.com/mucommander/jdk).

I suppose that recent changes that are included in that version of Java break on older versions of macOS or maybe it's related to the machine we build that version of Java on. I can try to see if there's a way to make it work on Catalina or Big Sur  but yeah, if it doesn't work I agree  it would make sense to document that muCommander cannot run on these unmaintained versions of macOs

**Comment by MeTalOneOEight** [comment] 2024-08-19 04:51
@ahadas It's most likely the machine you build Java on or better said Xcode version/SDK settings on it.
Xcode usually defaults to the current Apple supported OS versions, for older versions you need to change the target SDK (if it's even included since Apple is rather quick in removing SDKs from the current Xcode release).

**Comment by ahadas** [comment] 2024-08-19 06:10
@MeTalOneOEight the configuration of the machine (which is a GitHub hosted runner) can be found [here](https://github.com/mucommander/JRE/blob/master/.github/workflows/macos_x64.yaml). there was an issue to build on macOS 12 (Monterey) so [I switched to macOS 13](https://github.com/mucommander/JRE/commit/5a47b3a8cbfc2a9c4e0a0865260fa43c0d001e41). yeah, need to see if we can change the settings there..

**Comment by MeTalOneOEight** [comment] 2024-08-19 07:37
@ahadas I took a quick look at what the GitHub runner supplies, an older SDK is not included.
I don't know if it's possible to get the runner to use an older SDK manually.
This usually is done by copying it over from an older Xcode release.
Maybe it's easier to get your OpenJDK code changes accepted into the OpenJDK project so you don't need to keep your fork.
If it's too MacOS specific you may need to add platform condinational build macros so the build won't break on other platforms.

**Comment by ahadas** [comment] 2024-08-25 08:30
> Maybe it's easier to get your OpenJDK code changes accepted into the OpenJDK project so you don't need to keep your fork.

indeed, that's why[ I filed an issue for OpenJDK ](https://bugs.openjdk.org/browse/JDK-8314498) but they didn't accept the fix I posted back then. the good news is that [a fix was finally merged to OpenJDK last month](https://github.com/openjdk/jdk/pull/20144) but it seems it would only be available on Java 24 - @MeTalOneOEight could you check if you're able to install Java 24 on your operating system?

**Comment by MeTalOneOEight** [comment] 2024-08-25 08:46
@ahadas I did a quick look at the Info.plist of the jdk24 ea on openjdk.net, seems like it requires MacOS 11.
<key>JVMMinimumSystemVersion</key>
<string>11.00.00</string>

Not sure if other builds will require it too.

**Comment by MacTerrassa** [comment] 2024-08-28 20:50
Hello, my request was not only that they support old systems, but that they indicate which muCommander works or does not work on. While a version of Java didn't come with it, it might not have been so important to declare those requirements (although I think so), but now they are more important than ever as the application comes packaged with Java. I would also not require that they maintain a specific Java fork for muCommander, although it would be good, I understand that it may be very complicated as they have been commenting in previous messages. Simply indicating which systems it works from, I see it as sufficient. Especially when in Java it is not very clear which versions are required or not, or perhaps it depends on the specific implementation used, or the specific construction. When I looked there, 10.12 was mentioned but they haven't mentioned much else in a while either. For me, it is one of the fundamental reasons not to use third-party libraries. They make support very complicated, or they simply force you to be up to date without specifying much more.

**Comment by ahadas** [comment] 2024-09-22 14:13
@MeTalOneOEight @MacTerrassa @big610 thanks for the feedback on this one and on #1163.
to summarize the related changes so far:
1. the website shows `macOS (11+)` in the `Download` section
2. the `Requirements` section in the readme.txt file was refined to indicate muCommander is built for Java 11 but may require a newer version of Java when it comes with bundled Java (as part of the dmg, msi, deb, and rpm packages)

going forward, I think about packaging muCommander also with Java 17 in 1.5.1, which is supported on macOS 10.14.5 (Mojave), and then (1) above would change to show `macOS (10.14 / Mojave +)` and have two versions for Intel machines (with Java 17 and 24, and obviously the version with Java 17 won't have all the bug fixes)

what do you think?
I'd also appreciate if you can check the portable/tgz package as suggested in #1269

**Comment by big610** [comment] 2024-09-22 17:32
Thanks to everyone who helped figure out, @MeTalOneOEight @MacTerrassa 
Now that you know what the problem is, add it, to future versions. 
Add a new Headliner under the Version # & above What's Changed, called, System Requirements.
In What's Changed, label & mention appropriately. 
Your decision what is easier for how many versions or if making one Universal.
Some Developers type x86 & ARM code together so the version is Universal.
I can't find the link to check the portable/tgz package.

**Comment by ahadas** [comment] 2024-09-23 07:26
> Your decision what is easier for how many versions or if making one Universal. Some Developers type x86 & ARM code together so the version is Universal.

yep, we also have the same code for both x86 and ARM in muCommander but the JRE (Java Runtime Environment) differs.
 
> Releases: Add a new Headliner under the Version # & above What's Changed, called, System Requirements. In What's Changed, label & mention appropriately.
>
> Home page: mucommander / mucommander muCommander is a lightweight, cross-platform file manager with a dual-pane interface. It runs on any operating system with Java support (macOS, Windows, Linux, *BSD, Solaris...).
> 
> Official website: https://www.mucommander.com/ Right here, add the: System Requirements -your choice if one version or mutiple versions

are you aware of the description of the releases, including a readme file, [on GitHUb](https://github.com/mucommander/mucommander/releases)? for instance, here's [a link to the information for 1.5.0](https://github.com/mucommander/mucommander/releases/tag/1.5.0-1). I believe it includes all the information you look for so I can add a link to that on the website if you weren't aware of that

> 
> I can't find the link to check the portable/tgz package.

those are the rightmost versions in the `Download` section on the website (`Portable` and `Linux / Other`):
<img width="1115" alt="Screenshot 2024-09-23 at 10 18 06" src="https://github.com/user-attachments/assets/edf7424c-ac26-42be-a8a2-bce36de4ad0b">

**Comment by MeTalOneOEight** [comment] 2024-09-24 05:26
Can the app launcher be configured to use an already installed Java?
IIRC it was possible to remove the bundled Java with older releases of muCommander.
I tried with 1.4.0 when it didn't launch, but it didn't work without one in the app bundle.
That way you don't need to bundle a Java for older MacOS and cover more older versions.
Kinda like the portable in a Mac App version.

**Comment by ahadas** [comment] 2024-09-25 14:47
@MeTalOneOEight theoretically yes, but behind the scenes we use jpackage to create those artifacts and it seems like it kind of force us to comply with the best practice of embedding the JRE into the application image (if we don't specify one, jpackage would run jlink when creating a runtime image..).

I think the default (and recommended) dmg needs to have the JRE included (for the reasons jpackage does it - making the application easier to install, to be able to supply a JRE with the required features/fixes, and to test the app with the same runtime environment it runs with by end-users). however, it indeed sounds like a good idea to provide another dmg that instead of including older JRE, would act like the portable version (which will make it architecture-agnostic and since we keep compatibility with Java 11, should work on almost all Mac machines out there but easier to deploy/use than the portable version) - I can give it a try

**Comment by ahadas** [comment] 2024-09-26 10:51
ok, so thanks to @pskowronek we can get gradle-macappbundle back and use it to create a dmg that doesn't include JRE and as a result is architecture agnostic. needs to polish the PR a bit (e.g., to sign that dmg) though

**Closed** 2024-09-26 21:20 UTC

**Comment by ahadas** [comment] 2024-09-29 14:33
Version 1.5.1 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.5.1-1)
