### ISSUE TITLE
Settings that are stored in 'snapshot.xml' are lost

### ISSUE THREAD

**Issue by Andreas0602** [mucommander/mucommander#832] opened 2023-01-03 11:46 UTC
I'm creating a new issue for this, because #812 has been closed, and meanwhile I'm able to reproduce the problem with 100 % reliability. Here are the steps:

1. Make sure that you have configured some personal search and editor settings.
2. Close muCommander.
3. Start muCommander. As a result, the muCommander icon will appear in the dock.
4. Click on the muCommander icon in the dock. (This step is essential to reproduce the issue.)
5. Click on the red "x" in the upper left corner of the muCommander window. This will close muCommander.
6. Start muCommander. As a result, your personal search and editor settings will be gone.

Feel free to close this issue and re-open #812 instead.

**Comment by ahadas** [comment] 2023-01-14 16:05
I can't reproduce it on my machine, maybe that's related to latest macOS that I can't upgrade to at this point. @Andreas0602 can you share the log that covers the shutdown of the application?

**Comment by ahadas** [comment] 2023-01-14 21:41
@Andreas0602 thanks! I can't find anything in the log that might explain why muCommander failed to save or load the `snapshot.xml` file. I'll leave this issue open for some time, maybe someone else would be able to reproduce it

**Comment by ahadas** [comment] 2023-02-25 20:02
Duplicate of #812

**Closed by ahadas** 2023-02-25 20:02 UTC
