### ISSUE TITLE
macOS: "muCommander damaged and cannot be opened" v 1.3.0

### ISSUE THREAD

**Issue by Fido-vel-Fidel** [mucommander/mucommander#1022] opened 2023-08-02 10:49 UTC
Hi,
I have an error after update to 1.3.0 version on my mac macOS 13.4.1. After run I have this error "muCommander damaged and cannot be opened". I tried this solution:

Note: as the application is not signed, the following error may appear when trying to start is on macOS: "muCommander damaged and cannot be opened".
This can be solved by executing: sudo xattr -r -d com.apple.quarantine /Applications/muCommander.app

But problem still exist

**Comment by ahadas** [comment] 2023-08-02 15:54
Duplicate of #999

**Closed by ahadas** 2023-08-02 15:54 UTC
