### ISSUE TITLE
[Bug]  “muCommander.app” is damaged and can’t be opened

### ISSUE THREAD

**Issue by photocoder** [mucommander/mucommander#1026] opened 2023-08-04 02:10 UTC
### Description

Just download new muCommander for macOS and shows error 
**“muCommander.app” is damaged and can’t be opened. You should move it to the Bin.**
I tried both for a few times.
- v1.3.0 (dmg, 111 MB)
- v0.9.1 (Apple Java) (dmg, 27.8 MB)

### Steps to reproduce

Download, install, run - get error.

### Expected behavior

I expected it will work =)

### Actual behavior

It doesn't work. It even didn't run

### muCommander version

- v1.3.0 (dmg, 111 MB)
- v0.9.1 (Apple Java) (dmg, 27.8 MB)

### Java version

Installed Latest LTS Release Temurin™ jdk-17.0.8+7 for macOS aarch64

### Operating System type and version

MacBook Pro 16-inch, 2023 (Apple M2 Max)
MacOS Ventura Version 13.5 (22G74)

**Comment by ahadas** [comment] 2023-08-04 07:43
Duplicate of #999

**Closed by ahadas** 2023-08-04 07:43 UTC
Labels: bug
