### ISSUE TITLE
[Bug] How to enter private key in SSH connection ?

### ISSUE THREAD

**Issue by freebrowser1** [mucommander/mucommander#984] opened 2023-06-23 18:36 UTC
### Description

Using a server with SSH access and private key instead of password, I am unable to fill in a private key. I can only fill in a password. Other SSH/ SFTP clients do allow private key authentication.

### Steps to reproduce

See description.

### Expected behavior

Possibility to fill in a private key.

### Actual behavior

I cannot fill in a private key.

### Screenshots?

<img width="392" alt="Screenshot 2023-06-23 at 20 43 18" src="https://github.com/mucommander/mucommander/assets/26625141/96f8cc29-d9e5-4773-9a72-7a4814e818b1">

### muCommander version

1.2.0

### Java version

8.x

### Operating System type and version

Windows 11
macOS 13.x

### Relevant log output

```shell
1
```

**Comment by ssstain** [comment] 2023-06-25 19:44
How do you initiate an ssh connection? Is that SFTP you mean? SFTP is the only ssh-related connection I can see. There are private key and passphrase fields already.

**Comment by freebrowser1** [comment] 2023-06-26 14:58
Yes these are indeed available I now see, but it is refused.
When I ssh into this server vai a terminal or another SFTP client using the same private key, it does work. But using mucommander it issues errors 'too many connections' while it is not connected to any other ssh server.

<img width="492" alt="Screenshot 2023-06-26 at 16 50 56" src="https://github.com/mucommander/mucommander/assets/26625141/7c076965-3840-4ec4-814c-0de747a29951">

<img width="339" alt="Screenshot 2023-06-26 at 16 50 35" src="https://github.com/mucommander/mucommander/assets/26625141/0d8f4343-1ae9-4579-b136-4338d99413b8">

**Comment by freebrowser1** [comment] 2023-06-26 16:33
> Is `user` is `/Users/[user]/.ssh/id_rsa` a user on macOS that you are logged to you mac?
On the Ubuntu server it is the same username as the user on my Mac on which mucommander is running as client. So 'too many auth failures' is absolute nonsense as I can normally login with the same user id and private key using ssh terminal or Forklift sftp client.

**Comment by freebrowser1** [comment] 2023-06-27 05:55
> See the link, it might be sth with ssh client configuration in muC (too many tries with different other auth keys).
> 
> btw, do you have passphrase set for your id_rsa? Or is it empty?
The passphrase is empty. And that works with any other ssh / sftp client.

From that serverfault link:

> This could happen if you have (default on my system) five or more DSA/RSA identity files stored in your .ssh directory. In this case if the -i option isn't specified at the command line the ssh client will first attempt to login using each identity (private key) and next prompt for password authentication. However, sshd drops the connection after five bad login attempts (again default may vary).

But I don't have that many keys (ony two) in the .ssh directory.
Again, with other ssh / sftp clients it does work.

**Comment by ahadas** [comment] 2023-07-08 18:27
@freebrowser1 please check it with [version 1.3.0](https://github.com/mucommander/mucommander/releases/tag/1.3.0-1) that includes a fix for #892

**Comment by freebrowser1** [comment] 2023-07-09 15:38
Tried, but does not start at all.

<img width="296" alt="Screenshot 2023-07-09 at 17 35 48" src="https://github.com/mucommander/mucommander/assets/26625141/710a3df4-72ef-4b76-b47d-37c687df876a">

**Comment by ahadas** [comment] 2023-07-09 15:52
@freebrowser1 see https://github.com/mucommander/mucommander/issues/999#issuecomment-1627701479

**Comment by freebrowser1** [comment] 2023-07-10 16:00
`sudo xattr -cr /Applications/muCommander.app`

does not work. Same issue.

**Comment by ahadas** [comment] 2023-07-10 19:17
@freebrowser1 we've diverged from the original topic of this issue..

> Why can the app not be pre-notarized by the developer ?

it can and previous versions were signed but in order to sign an application, one needs to have a developer account. I've discovered that my account expired while creating the 1.3.0 release. such a developer account is not free and I found that I didn't use it besides signing three releases of muCommander - so in my opinion it doesn't worth the cost. but if you think otherwise, you're invited [to sponsor the project](https://github.com/sponsors/mucommander) and when it covers the cost of a developer account, I'd gladly sign the application

> Other open source apps for macOS are ready to use.

each project is different, e.g., I contribute to oVirt that was backed by Red Hat. muCommander, on the other hand, is not backed by any company and everyone that participate in muCommander does it in their spare time and without being paid for their efforts.

if you find a way to sign an open source application for free, please share how to do this.

> I use macOS 13.4.1 on an M1, is that too old ?

of course 13.4.1 is not too old :)
[we managed to install it on 13.4.1](https://github.com/mucommander/mucommander/issues/999#issuecomment-1628942908) and it works properly 


back to the original issue, it can also be tested using the portable/tgz version on macOS if you like
I'm closing this issue as a duplicate of #892 , please reopen if it still doesn't work with version 1.3.0

**Closed by ahadas** 2023-07-10 19:17 UTC
Labels: bug

**Comment by freebrowser1** [comment] 2023-07-11 19:20
Resolved. It worked under macOS 13.4.1 after allowing it in Security&Privacy. And sftp connect to ssh server now also works with private key.
