### ISSUE TITLE
Freezes on OS X El Capitan 10.11.6 

### ISSUE THREAD

**Issue by liry** [mucommander/mucommander#35] opened 2016-08-26 09:54 UTC
Cca every 10th time I try to enter some directory, the whole application freezes. The "progress bar over the address line" is cca in 3/4.

v0.9.0, OS X 10.11.6 (15G31)

**Comment by ahadas** [comment] 2016-09-02 18:50
Hi @liry ,
I'll need to be provided with some more information on how to reproduce this since the application does not freeze by simply entering to some directory many times on my machine.
Do you use tabs and switch between them maybe? because I fixes a deadlock that caused the UI to freeze while switching between tabs and this fix is not included in 0.9.0.
I would also suggest to try 0.9.1rc as it seems to be pretty stable by now:
https://github.com/mucommander/mucommander/releases/tag/0.9.1rc

**Comment by ahadas** [comment] 2016-10-31 20:28
closing this as I cannot reproduce it. feel free to reopen if it still happens with 0.9.1 and more information can be provided.

**Closed by ahadas** 2016-10-31 20:28 UTC
