### ISSUE TITLE
File copying hangs.

### ISSUE THREAD

**Issue by demetriuzz** [mucommander/mucommander#408] opened 2021-02-03 09:06 UTC
I use **muCommander** for copy file to another computer _over_ the network (**sftp**).

Use version: 0.9.6 (Build date: 2021/01/02 Build number: b64d056)
**Java**: 11.0.9.1 (OpenJDK 64-Bit Server VM 11.0.9.1+1-post-Debian-1deb10u2 Debian)
**OS**: Linux Debian 4.19.0-14-amd64

### Screenshot
![mucommander_0 9 6_copy_test_20210203](https://user-images.githubusercontent.com/61899867/106722463-cf250680-6627-11eb-859b-af490f47c447.png)

File is small - 37MB, network 100Mb.

### SCP command
If use console command `scp` then the all process takes **3** seconds.
Command output: `100%   37MB  11.2MB/s   00:03`

### Question
Why?

### Assumption
This JAVA network problem.

**Comment by ahadas** [comment] 2021-02-03 10:22
hi @demetriuzz,
it was suggested that [we can make a change from our side to improve it](https://github.com/mucommander/mucommander/issues/345#issuecomment-770279396). would you be willing to test a nightly build with the proposed change?

**Comment by demetriuzz** [comment] 2021-02-03 10:46
Good day @ahadas !
I'm in no hurry.
I'll wait for the **release**.

**Comment by ahadas** [comment] 2021-02-05 21:40
Duplicate of #345

**Closed by ahadas** 2021-02-05 21:40 UTC

**Comment by ahadas** [comment] 2021-05-08 14:09
v0.9.7 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/0.9.7-1)

**Comment by demetriuzz** [comment] 2021-05-10 03:50
> v0.9.7 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/0.9.7-1)

Thank you!
