### ISSUE TITLE
opening a specific directory via commandline opens two windows

### ISSUE THREAD

**Issue by hupfdule** [mucommander/mucommander#218] opened 2019-07-12 08:29 UTC
If I call mucommander without any parameters:

```
mucommander
```
, it opens 1 window with the last opened directories, e.g. `/usr/share/doc/` and `$HOME`.

If I instead specify a certain directory to open:

```
mucommander /etc
```

it opens 1 window with the last opened directories (e.g. `/usr/share/doc` and `$HOME`), and a 2nd window with the specified directory (e.g. `/etc` and `$HOME`).

Related to that problem is, that the 2nd window i reduces to its minimum size, which in my case (Enlightenment filemanager under Debian Buster) is a very short titlebar with no actual visible window space.

The correct behaviour would be to open just the 2nd window, but that one in the correct size.

**Comment by kousalik** [comment] 2019-07-15 10:38
Same happens to me. Then it opens 3 windows, 4 windows etc. I'll look what I can do.

**Comment by kousalik** [comment] 2019-07-17 03:20
@ahadas I think I know where the problem is and started working on a fix. The commander in this case creates the new windows and at the same time reads the snapshot and recoveres windows from the last state. This leads to n+1 windows being created each time you do that.

My question before submitting a fix is, what is the expected behaviour when running with folder parameter? My expectation would be the same as @hupfdule. Opening ONLY the new window in the specified folder, ignoring the last snapshot. Cheers

**Comment by ahadas** [comment] 2020-04-04 15:20
Fixed in version 0.9.4 by #224  and #227

**Closed by ahadas** 2020-04-04 15:20 UTC
