### ISSUE TITLE
Connect to server have some bugs on fedora.

### ISSUE THREAD

**Issue by Hammer2900** [mucommander/mucommander#769] opened 2022-10-10 10:51 UTC
Connect to server, when open s3 folder i see all bucket but when click on folder get error unable read folder content.
Also, i try to connect dropbox and gdrive, browser not open page where i can login to my account, but if i terminate main process(kill) i see all these invitations appearing in the browser.
And if install rpm package with dnf, app installed but when i type in console first liters(mucom) i cannot find exe with TAB key.

Fedora 35
muCommander v1.1 portable

**Comment by ahadas** [comment] 2022-10-11 19:35
@Hammer2900 I see three different issues reported here but I can't reproduce them and there's not enough information on any of them, so I'm closing this issue but please feel free to file new issues on particular things you can provide more information on

> Connect to server, when open s3 folder i see all bucket but when click on folder get error unable read folder content.

I'll need a reproducer or at least the log with the error (can be found in `~/.mucommander/logs`)

> Also, i try to connect dropbox and gdrive, browser not open page where i can login to my account, but if i terminate main process(kill) i see all these invitations appearing in the browser.

this means that the application tried to open the URL but for some reason the new tab was not added in the browser. it happened to me long time ago but not with the recent changes (I'm using Fedora 36 btw)

> And if install rpm package with dnf, app installed but when i type in console first liters(mucom) i cannot find exe with TAB key.

not sure what you mean here - do you mean that you don't get auto-completion for 'mucommander' in the terminal? if so, the executable is located in `/opt/mucommander/bin/`, you'll need to add it to your path or type the whole path (`/opt/mucommander/bin/muCommander`)

**Closed by ahadas** 2022-10-11 19:35 UTC
