### ISSUE TITLE
“muCommander.app” is damaged and can’t be opened. You should move it to the Trash - jre-8u333 - build 1.0.0-1 - Mac OS Monterey 12.4

### ISSUE THREAD

**Issue by realaaa** [mucommander/mucommander#662] opened 2022-05-31 06:38 UTC
hi all !

muCommander prompted there is a new version available, so I got it - then got the error mentioned above

updated Java 

%  /Library/Internet\ Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java -version
java version "1.8.0_333"
Java(TM) SE Runtime Environment (build 1.8.0_333-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.333-b02, mixed mode)

re-downloaded and re-installed couple times, no luck!

eventually just did the xattr -cr to remove the attribute and it launched

why is this happening?

**Comment by ahadas** [comment] 2022-05-31 07:12
Hi @realaaa , please check out #613 - that's a known issue
Duplicate of #656

**Closed by ahadas** 2022-05-31 07:12 UTC
