### ISSUE TITLE
Files are not copied to clipboard properly on macOS

### ISSUE THREAD

**Issue by engilyin** [mucommander/mucommander#239] opened 2019-08-13 21:47 UTC
It could be really useful to have the cut/copy/paste files and dirs functionality.
Accessible form context menu, toolbar, standard shortcats(Ctrl/Command+XCV) and main menu.

I found copy file in the context menu but seems like it has another meaning. 

The CUT could be very useful if you are working in single pane mode. Or want to paste it into other app(E.g. Finder/Explorer/Favorite IDE etc)

**Comment by LeeBinder** [comment] 2022-05-09 21:06
@ahadas I thought this was implemented at some point already, but I just realize it's not working in v.1.0.0-1 macOS.

Can you share the status quo of this feature with us, please?

**Comment by djonathanmodel** [comment] 2022-12-06 13:41
@LeeBinder Since OP didn't answer, I'm going to answer for him. I'm running v.1.1.0 of MuCommander under MacOS and the shortcut doesn't even exist. Is it only a MacOS issue or is it fully known under every platform?

**Comment by LeeBinder** [comment] 2022-12-06 21:44
Hi @djonathanmodel . I'm running muC. v.1.2.0 latest snapshot in macOS: same thing, still no "Cut" option in the menu. Cmd+X only offers to move to the dir in the other pane, which is not the native cut&paste functionality.

I haven't checked in Windows yet.

@ahadas ?

**Comment by LeeBinder** [comment] 2023-03-11 21:32
@ahadas Thank you for v.1.2.0.1 final. I have hopes you would finally enable native cut & paste via Ctrl-/Command +X -> +V in v.1.3.0 👍

**Comment by ahadas** [comment] 2023-08-06 06:04
I'm changing the scope of this bug:

adding a `cut` operation is problematic since I think we shouldn't remove the file until it's pasted and Java doesn't seem to notify an application when the file is pasted outside of the application. specifically under macOS there's no need for `cut` operation since the file is removed from the source when pasting the file with META+ALT+V (i.e., the operation is turned to `move` rather than `copy`). so this part is dropped.

as for `I found copy file in the context menu but seems like it has another meaning.` which is also what #982 refers to, that's a regression with newer version of macOS that wasn't fixed in OpenJDK but I saw there's [a fix for that by JetBrains](https://github.com/JetBrains/JetBrainsRuntime/commit/794449e338450c93d05c665fa8043aee98835e8e) that we can use.

**Closed** 2023-08-06 06:32 UTC
Labels: enhancement

**Comment by ahadas** [comment] 2024-05-02 21:32
Version 1.4.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.4.0-1)

**Comment by LeeBinder** [comment] 2024-05-02 22:01
Thank you very much for the new version with it's huge change list, but regarding this issue: sorry, I still don't see an entry for "Cut" .. :(

![Bildschirmfoto 2024-05-02 um 23 59 13](https://github.com/mucommander/mucommander/assets/39203497/1860045a-f194-4b5b-84aa-ed28080938dd)

**Comment by ahadas** [comment] 2024-05-02 22:44
@LeeBinder you're correct - the fix was only about copying a file from muCommander to Finder. CUT optleration was not added and I'm not sure I understand the issue with META+ALT+V

**Comment by LeeBinder** [comment] 2024-05-02 23:31
On a Mac keyboard there is no META key, only Cmd. (Command), Alt/ Option and Ctrl. (Control). After copying a file, I tried all possible keys vicariously for META, to no avail: only copy, no move.

**Comment by ahadas** [comment] 2024-05-03 05:43
@LeeBinder ah ok, I see what you meant now - the META key corresponds to the Cmd key on Mac keyboard
could you do the following test:
1. In muCommander, copy a file
2. In Finder, open the "Edit" item at the top menu and press cmd+alt - the `Paste Item` item should change to `Move Item Here` and there will be a shortcut key next to it - which shortcut appears for you there?

**Comment by LeeBinder** [comment] 2024-05-03 07:00
⌥⌘V

I've read your comment above. Still, if Finder can, muC shouldn't lag behind in this regard. Hopefully you find a way to implement this basic functionality somehow.

**Comment by ahadas** [comment] 2024-05-03 08:02
> ⌥⌘V

ok, that's META+ALT+V in our "terminology" - it's weird if this doesn't trigger moving a file that was copied to the clipboard from muCommander for you

> I've read your comment above. Still, if Finder can, muC shouldn't lag behind in this regard. Hopefully you find a way to implement this basic functionality somehow.

I'm afraid that's beyond our control, that's something that would require changes in Java - if you find this helpful, I'd suggest to file an issue to OpenJDK

**Comment by LeeBinder** [comment] 2024-05-03 09:06
@ahadas sorry, maybe I expressed myself unclearly: muC ⌘C -> Finder ⌥⌘V works as supposed. What I meant is what's being discussed here = ⌥⌘V aka ⌘X functionality still not present in muC.

@Andreas0602 great idea and find. So there is light at the end of the tunnel (and it's not a train ;) )

**Comment by ahadas** [comment] 2024-05-03 09:19
> Hmm, I'm not a Java expert at all, but I asked Google Gemini Advanced `How to move a file that has been copied to the clipboard to a new location in Java?` just out of interest, and the answer at least looks like it makes sense. @ahadas, let me know if you're interested in that answer.

Sure, what does it say?

**Comment by ahadas** [comment] 2024-05-03 19:54
@Andreas0602 thanks, but this seems to cover the opposite direction, i.e., when one copies a file to the clipboard and then paste it with Java. it's a simpler flow since when we're provided with the path of the source file, we can simply delete the source file after copying its content to the destination file. however, when copying a file from Java and pasting it in Finder, there needs to be a way to indicate Finder that we wish to remove the file at the end of the process

**Comment by LeeBinder** [comment] 2024-05-03 21:03
@Andreas0602 100% correct. Two additions:

1. on the same disk, directly move not a) copy then b) delete, for obvious reasons which don't need to be re-hashed
2. I really don't see why in muC this functionality should / would need to be implemented via ⌥⌘V. The way Apple Finder handles this is the way Apple Finder handles this.. To stay streamlined with Windows and Linux, ⌘X -> ⌘V are the keyboard combos at hand for macOS, analog to XtraFinder, TotalFinder, (legacy) Finder Cut & Paste scripts etc.

**Comment by ahadas** [comment] 2024-05-04 09:40
@Andreas0602 @LeeBinder ok, now I see why we were not on the same page here
the reporter wrote:
`The CUT could be very useful if you are working in single pane mode. Or want to paste it into other app(E.g. Finder/Explorer/Favorite IDE etc)`
please note two things:
1. this came after `I found copy file in the context menu but seems like it has another meaning` - which was correct, there was an issue with copying files to the clipboard that affected all operations that made use of that content. this part was resolved by the fix for this issue
2. note the "Or want to paste it into other app" part, I didn't find a way to place the content of the file in the clipboard with an indication that the source file should be deleted as part of the "paste" operation to address this

now you guys seem to refer to a particular case in which both CUT and PASTE operations are done within muCommander. I wouldn't like to introduce CUT operation that is specific to muCommander (i.e., when pasting the file elsewhere, the operation would be "copy" rather than "move") and I, for one, don't see much value in this - "move" operation has several advantages over going through the clipboard (but I also don't use single pane mode..). so I'd suggest to file a new issue about this case, and we can keep discussing / thinking about this.
