### ISSUE TITLE
Drag and drop of documents from any folder into Apple Mail hangs Mail

### ISSUE THREAD

**Issue by neilyoung** [mucommander/mucommander#859] opened 2023-01-26 14:23 UTC
Since Ventura, btw.
Drag and drop from Finder - no problem.

**Comment by hannesvei** [comment] 2023-09-21 14:41
I just got a new machine with MacOS Ventura an see the same behaviour.

Does someone know a workaround?

I am very used to drag and drop from mucommander into macos Mail.

Regards Hannes

**Comment by neilyoung** [comment] 2023-09-21 14:43
You can always attach using the menu way in mail, that works.

**Comment by ahadas** [comment] 2023-09-21 19:16
Can any try that with the nightly version please?

**Comment by neilyoung** [comment] 2023-09-22 20:19
> Can any try that with the nightly version please?

No way to run this on my system. "App damaged". Even with gatekeeper disabled.

**Comment by pskowronek** [comment] 2023-09-22 21:01
> > Can any try that with the nightly version please?
> 
> No way to run this on my system. "App damaged". Even with gatekeeper disabled.

See #999 for solutions.

**Comment by neilyoung** [comment] 2023-09-23 15:45
Yes, that worked. I recalled that I had to do this in the past already, forgot about...

The problem is not solved. I could attach two images to two mails, and then the third attempt hung Mail again.

**Comment by pskowronek** [comment] 2023-09-23 16:53
> Yes, that worked. I recalled that I had to do this in the past already, forgot about...

Great

> The problem is not solved with 1.4. I could attach two images to two mails, and then the third attempt hung Mail again.

Can you take a look in logs (`~/Preferences/muCommander/logs/mucommander.log` or via muC -> Help -> Debug console) - maybe there's something interesting when it happens?

> Nevermind. I tend to blame Apple for that. MacOS is getting more and more Windows witch each update. :/

Maybe, maybe not. I will try to reproduce that (on Catalina) later today.

**Comment by pskowronek** [comment] 2023-09-23 16:59
btw, what type of file you try to drag and drop? How big they are? How many at a time?

**Comment by neilyoung** [comment] 2023-09-23 17:30
> btw, what type of file you try to drag and drop? How big they are? How many at a time?

I don't think the file type/file size matters. I happens with PDF, JPEG, PNG etc. This time at first shot while trying to d&d a 1.8 MB JPEG scan from my printer. Debug console after hang:

<img width="1375" alt="image" src="https://github.com/mucommander/mucommander/assets/731020/60ba79ef-d93b-4a28-b0b1-5ddfd49ce469">

**Comment by ahadas** [comment] 2023-09-23 19:34
@pskowronek I don't think we'll see anything about that in muCommander itself - I saw this when working on https://github.com/mucommander/mucommander/issues/239, once the data was copied to the clipboard and the other client (in that case Finder) tried to access it, the error didn't propagate to muCommander. I thought that fix could help with this issue, but if some files are attached properly, I think this might really be an issue with the Mail application

**Comment by neilyoung** [comment] 2023-09-24 05:49
@ahadas Just a reminder: Mail has no issues if drag and drop is done from finder, so I wouldn't take mu completely out of the game.

**Comment by pskowronek** [comment] 2023-09-24 20:24
@neilyoung tried to reproduce and nothing. Do you have any antivirus or other scan tool?

**Comment by neilyoung** [comment] 2023-09-24 21:09
Sure. Avira. But don't bother. I can live with that

**Comment by pskowronek** [comment] 2023-09-24 21:10
@neilyoung can you disable Avira for a moment and try?

**Comment by neilyoung** [comment] 2023-09-24 21:52
Will do tomorrow and report

**Comment by neilyoung** [comment] 2023-09-25 06:41
Without and with Avira on no problem too right now. But I just had one JPEG to test (couldn't access my other folders, missed somehow the query)

**Comment by neilyoung** [comment] 2023-09-25 06:46
Wait. Tried another file, a PDF. Now it just works with Avira switched off... Maybe you got the reason for the fail .

**Comment by pskowronek** [comment] 2023-09-25 15:55
Maybe Avira is blocking attachments (drag n drop files) from unsigned apps? Are you able to check logs or reports of Avira, maybe there's something that may shed some light.

**Comment by neilyoung** [comment] 2023-09-25 15:56
Its not blocking from finder to mail

**Comment by pskowronek** [comment] 2023-09-25 18:25
@hannesvei do you have any antivirus?

**Comment by neilyoung** [comment] 2023-09-27 15:39
Thanks for fixing this. Where can I download it? What is the build number referencing too? Sorry if this is a stupid question

**Comment by pskowronek** [comment] 2023-09-27 16:48
> Thanks for fixing this. Where can I download it? What is the build number referencing too? Sorry if this is a stupid question

There is no additional fix for your problem with AV @neilyoung. @hannesvei has just checked if his problem is fixed.

**Comment by pskowronek** [comment] 2023-09-27 17:40
@neilyoung but if you could check AV reports / logs if it is being blocked, then it may shed some light how to tackle the problem :)

**Comment by neilyoung** [comment] 2023-09-27 18:01
Not sure where to find this and if there is such a trace at all...

BTW: Today I attached several PDF and no issue (Avira active in background). It happens out of the sudden, once in a while. Hard to catch.

**Comment by neilyoung** [comment] 2023-09-29 06:49
Made some more tests this morning. Avira was a "false friend". The mail hangs on drag and drop don't have to do with the scanner, IMHO. It happens with and w/o Avira running

**Comment by hannesvei** [comment] 2023-10-12 07:18
I had to observe a somewhat odd behaviour.

My first impression of using nightly build 2023/09/21 was positiv. In the meantime I had to observe that sometimes the drag and drop works as expected sometimes not.

Where can I find some log File to dig deeper?

Regards Hannes

**Comment by ahadas** [comment] 2023-10-12 07:22
@hannesvei where did you drop the files, is it in a separate application(s)?

**Comment by hannesvei** [comment] 2023-10-12 08:07
My workflow is from mucommander -> Apple Mail

**Comment by neilyoung** [comment] 2023-10-12 08:18
This "sometimes ist works, sometimes not" is confirmed.

**Comment by ahadas** [comment] 2024-08-16 19:45
@hannesvei @neilyoung could it be that it fails when dragging a file that is not a local file? I couldn't reproduce it but the proposed fix for #1240 may address this issue as well, could you please try [this nightly build](https://github.com/mucommander/mucommander/actions/runs/10425258414)?

**Comment by neilyoung** [comment] 2024-08-16 19:47
@ahadas It's always a local file

**Comment by ahadas** [comment] 2024-08-16 19:52
> @ahadas It's always a local file

ack, I'd appreciate feedback on the aforementioned nightly build, if the issue still reproduces on your machine

**Comment by neilyoung** [comment] 2024-08-17 09:46
> > @ahadas It's always a local file
> 
> ack, I'd appreciate feedback on the aforementioned nightly build, if the issue still reproduces on your machine

I would, but I don't currently know where to find the nightlies... ATM I only see a release 1.5.0, but this is not what you mean, or?

**Comment by ahadas** [comment] 2024-08-17 11:05
@neilyoung ah yeah, I didn't bump the version in build.gradle so it appears as 1.5.0 in the link above, but the artifacts there, including the dmg files, have the latest changes from the `master` branch

**Comment by neilyoung** [comment] 2024-08-17 11:25
OK, installed. Made three attempts. No issue so far. Will report if I catch one. Thanks a lot

**Comment by neilyoung** [comment] 2024-08-26 07:32
Not directly related to this issue, but with this version I now have a big white additional window in the back when I open a terminal. My terminal open string is `open -a Terminal .`

<img width="2056" alt="image" src="https://github.com/user-attachments/assets/026a7da2-e2a8-43a0-ad28-b95f09587e9a">

**Comment by pskowronek** [comment] 2024-08-26 16:51
> My terminal open string is `open -a Terminal .`

This is not a correct way - you told MuC to execute this command that ... opens Terminal as an app. 
You must provide a path to _shell_, either `/bin/bash` or `/bin/zsh` possibly with `--login` (or any other shell you like).

**Comment by neilyoung** [comment] 2024-08-26 16:54
But it worked like so for years

**Comment by pskowronek** [comment] 2024-08-26 17:24
> But it worked like so for years

Now in muC there's built-in terminal, not an external window to execute a command and that's it, or outside app. If you really need Terminal app as external application, they you probably need to define a custom command (https://github.com/mucommander/mucommander/wiki/Custom-Commands)

**Comment by neilyoung** [comment] 2024-08-26 17:26
> > But it worked like so for years
> 
> Now in muC there's built-in terminal, not an external window to execute a command and that's it, or external app. If you really need Terminal app as external application, then you probably need to define a custom command (https://github.com/mucommander/mucommander/wiki/Custom-Commands)

No, I would rather step back one version in order to have that again :) I like the Terminal app more than the internal terminal

**Comment by neilyoung** [comment] 2024-08-26 17:29
...and from all I can say it works as expected in 1.3.0. Just the terminal app window with muCommander in the background.

Good for me

**Comment by ahadas** [comment] 2024-09-01 11:28
about the terminal, I agree with @pskowronek that now that we have a built-in terminal, it make more sense to set a custom command in order to open an external terminal - but as noted above, that's a different topic

as for this issue with drag and drop to the Mail application in macOS, I'm closing this as the fix for #1240  seems to fix that as well - feel free to reopen if it still reproduces

**Closed by ahadas** 2024-09-01 11:28 UTC
Labels: macOS Ventura

**Comment by neilyoung** [comment] 2024-09-02 04:52
Unfortunately this integrated terminal is not an adequate replacement for a real terminal, since I can only open one (AFAIK). But never mind. I will return to 1.3.0

**Comment by ahadas** [comment] 2024-09-29 14:32
Version 1.5.1 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.5.1-1)
