### ISSUE TITLE
[Bug] MacOS: muCommander is damaged and can't be opened

### ISSUE THREAD

**Issue by hflocken** [mucommander/mucommander#1042] opened 2023-08-14 06:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues (including the closed ones)

### Description

I have downloaded the latest 1.3.0 update of muCommander and installed it n my Mac. However, when I want to start muCommander , I get the following error message:
<img width="248" alt="image" src="https://github.com/mucommander/mucommander/assets/43062232/c1cc3be7-d11b-414c-9a7c-d53d80b4722c">

The same error shows up when use the normal as well as the Java version. I did not have any issues in installing previous version of muCommander.

### Steps to reproduce

Download DMG File
Install muCommander
Start muCommander

### Expected behavior

muCommander starts without an error

### Actual behavior

Error as shown above is displayed

### muCommander version

1.3.0-1

### Java version

n/a

### Operating System type and version

Ventura 13.4.1

### Relevant log output

```shell
n/a
```

**Comment by ahadas** [comment] 2023-08-14 07:16
Duplicate of #999

**Closed** 2023-08-14 07:26 UTC
Labels: bug
