### ISSUE TITLE
Azul Zulu 17 jre - mucommander does not run

### ISSUE THREAD

**Issue by b-user** [mucommander/mucommander#505] opened 2021-09-18 11:37 UTC
Hellow.
I try run mucommander-0.9.7 at  zulu17 (at clean install windows 10 x64)

1. unpack zulu17.28.13-ca-jre17.0.0-win_x64.zip to C:\bin\java\jre17
2. create registry entry 
 [HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft\Java Runtime Environment\17]
"JavaHome"="C:\\bin\\java\\jre17"
3. add variable:
setx JAVA_HOME C:\bin\java\jre17\
4. add to %path% variable C:\bin\java\jre17\bin\
5. unpack mucommander-0.9.7-1-portable.zip  to  C:\bin\mucommander
6. and run cmd /k  java -jar C:\bin\mucommander\mucommander-0.9.7.jar

as result - text:
Exception in thread "main" java.lang.reflect.InaccessibleObjectException: Unable to make protected java.lang.Object java.util.AbstractMap.clone() throws java.lang.CloneNotSupportedException accessible: module java.base does not "opens java.util" to unnamed module @14514713
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source)
        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Unknown Source)
        at java.base/java.lang.reflect.Method.setAccessible(Unknown Source)
        at com.beust.jcommander.Parameterized.parseArg(Parameterized.java:123)
        at com.beust.jcommander.JCommander.addDescription(JCommander.java:601)
        at com.beust.jcommander.JCommander.createDescriptions(JCommander.java:594)
        at com.beust.jcommander.JCommander.<init>(JCommander.java:249)
        at com.beust.jcommander.JCommander.<init>(JCommander.java:235)
        at com.beust.jcommander.JCommander.<init>(JCommander.java:227)
        at com.mucommander.main.muCommander.main(muCommander.java:213)

If i doubleclick mucommander.exe - there are no visible events happening

**Comment by b-user** [comment] 2021-09-18 11:45
i try run mucommander-0.9.8-snapshot-portable.zip
as result:
java.lang.ClassCastException: class org.slf4j.helpers.SubstituteLogger cannot be cast to class ch.qos.logback.classic.Logger (org.slf4j.helpers.SubstituteLogger is in unnamed module of loader org.apache.felix.framework.BundleWiringImpl$BundleClassLoader @19e05161; ch.qos.logback.classic.Logger is in unnamed module of loader org.apache.felix.framework.BundleWiringImpl$BundleClassLoader @544add2a)
 at com.mucommander.utils.MuLogging.configureLogging(MuLogging.java:144)
 at com.mucommander.Application.run(Application.java:289)
 at com.mucommander.Application.run(Application.java:495)
 at com.mucommander.Activator.start(Activator.java:102)
 at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:698)
 at org.apache.felix.framework.Felix.activateBundle(Felix.java:2402)
 at org.apache.felix.framework.Felix.startBundle(Felix.java:2308)
 at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1539)
 at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
 at java.base/java.lang.Thread.run(Unknown Source)

**Comment by ahadas** [comment] 2021-09-18 20:14
Hi,
The first issue was addressed on the master branch (#465).
I can't reproduce the second issue - do you see `logback-classic` and `logback-core` in the `bundle` folder?

**Comment by ahadas** [comment] 2021-12-20 20:36
Closing, feel free to reopen if more information can be provided

**Closed by ahadas** 2021-12-20 20:36 UTC

**Comment by rvansa** [comment] 2022-12-07 10:13
Just tried to run mucommander on OpenJDK 17, the same error appears as in the original comment.

@ahadas Non-members probably do not have the permission to reopen the issue.

**Comment by ahadas** [comment] 2022-12-07 13:14
@rvansa so you're also used Azul? on which operating system?

**Comment by rvansa** [comment] 2022-12-08 09:19
I've tried to install the RPM from web (1.1.0) but that didn't work for me at all, the binary did not print anything and just exited. The portable version from Github (1.2.0) works for me.

**Comment by pskowronek** [comment] 2023-06-09 21:40
Is it still an issue?
