### ISSUE TITLE
[Bug] Rename/create new dir (F7) using Mac OS does not work

### ISSUE THREAD

**Issue by rschu68** [mucommander/mucommander#1086] opened 2023-12-13 07:47 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues (including the closed ones)

### Description

Creating and renaming directory using F-keys does not work

### Steps to reproduce

When using muCommander with latest version of MacOs 14.1.2 (M2 pro) using F7 pop ups the "new directory" window but i cannot enter anything in the field .. not possible.
Renaming a directory with right-click rename seems to do nothing. Clicking with mouse multiple times on the dir-name seems to work.

### Expected behavior

Renaming works, creating new directorys works

### Actual behavior

Does not work

### muCommander version

muCommander
Version: 1.4.0
Build date: 2023/12/05
Build number: 90a41ce

### Java version

Java
Runtime version: 20-internal
VM name: OpenJDK 64-Bit Server VM
VM version: 20-internal-adhoc.ahadas.jdk
VM vendor: Oracle Corporation

### Operating System type and version

Name: Mac OS X
Version: 14.1.2
Architecture: x86_64

**Comment by NeekonMike** [comment] 2023-12-19 19:39
Standard 1.3.0 install on M2 macOS 14.2 works as expected for me.

**Comment by rschu68** [comment] 2023-12-19 21:23
> Standard 1.3.0 install on M2 macOS 14.2 works as expected for me.

:) but not for me.. LOL

**Comment by pskowronek** [comment] 2023-12-19 22:10
> > Standard 1.3.0 install on M2 macOS 14.2 works as expected for me.
> 
> :) but not for me.. LOL

You got muC Version: 1.4.0, @NeekonMike tried 1.3.0. Can you check 1.3.0?
Any chance you could record a video of the problem? Or check the logs via muC->help.

**Comment by ahadas** [comment] 2023-12-22 09:45
> You got muC Version: 1.4.0, @NeekonMike tried 1.3.0. Can you check 1.3.0? Any chance you could record a video of the problem? Or check the logs via muC->help.

yeah, the nightly build (1.4.0) [uses a different version of Java for macOS](https://github.com/mucommander/JRE/commit/91c62f5d89c9473324c68eedad40640480f10d79) so it could be a regression in the nightly build

**Comment by rgerrits** [comment] 2024-07-16 20:14
I'm seeing the same behaviour on a Macbook M3 Pro running Sanoma 14.5, with MuCommander 1.4.0
(Build date: 2024/05/02 Build number: cb8caf0)

the problem is that if you click on the "Make Directory (F7)" with the mouse, then MuCommander shows a green box with the text "Make Directory: F7" and this green box seems to steal the focus from the popup, preventing to type text.
Even clicking in the text-box doesn't restore focus. The text-box seems read-only.

Pressing the F7 key on the keyboard works fine though. (and doesn't show the green box)

Similarly: When selecting a file and then pressing F6 on the keyboard gives the move dialog, with the filename highlighted -> this allows to easily rename a file during move.
However when clicking F6 with the mouse, it again shows the green box, stealing focus -> filename is no longer highlighted and the entire text box seems readonly

**Comment by ahadas** [comment] 2024-07-23 20:16
thanks @Andreas0602 and @rgerrits for the confirmation that this works now, closing

**Closed by ahadas** 2024-07-23 20:16 UTC
Labels: bug
