### ISSUE TITLE
broken codesigning on 1.0.0-1 / macOS

### ISSUE THREAD

**Issue by core-code** [mucommander/mucommander#618] opened 2022-04-21 08:53 UTC
```
spctl -vvvv --asses /Volumes/muCommander/muCommander.app 
/Volumes/muCommander/muCommander.app: code has no resources but signature indicates they must be present
```

**Comment by Tayphoon** [comment] 2022-04-22 06:36
Same here

**Comment by ahadas** [comment] 2022-04-22 15:03
Yeah, makes sense, see [this](https://github.com/mucommander/mucommander/discussions/613#discussioncomment-2601769). Closing as a duplicate of #613

**Closed by ahadas** 2022-04-22 15:03 UTC
