### ISSUE TITLE
Sequoia firewall problem

### ISSUE THREAD

**Issue by flyingdrill** [mucommander/mucommander#1270] opened 2024-09-24 20:01 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues (including the closed ones)

### Description

Sequoia's firewall blocks incoming connections from MuCommander.   I cannot see a way to reverse this.

### Steps to reproduce

As above.  I do not have to do anything!

### Expected behavior

Why is Apple's firewall doing this?

### Actual behavior

I will not see any updates or messages from MuCommander

### Screenshots?

<img width="316" alt="Screenshot 2024-09-24 at 21 00 37" src="https://github.com/user-attachments/assets/ace2c7d3-d18a-4d0b-9905-3176ec4802a3">

### muCommander version

1.5.0

### Java version

Runtime version 23

### Operating System type and version

Mac OS Sequoia 15.0

**Comment by pskowronek** [comment] 2024-09-24 21:15
You mean "Sequoia's firewall blocks incoming connections _to_ MuCommander"? 
Can you provide exact steps to reproduce?

This thread might help - Firefox was blocked from accessing local network: https://www.reddit.com/r/mac/comments/1fif1gr/firefox_no_longer_works_after_upgrading_to_macos/

**Comment by ahadas** [comment] 2024-12-31 09:30
@flyingdrill does it still happen? it doesn't seem to reproduce on my machine installed with Sequoia 15.2

**Comment by pskowronek** [comment] 2024-12-31 11:05
@ahadas I bet it was a bug in Sequoia

**Comment by ahadas** [comment] 2024-12-31 11:16
> @ahadas I bet it was a bug in Sequoia

yeah, could be
and in either case it's not a bug in muCommander so let's close this issue as `can't repro`

**Closed by ahadas** 2024-12-31 11:16 UTC
Labels: bug
