### ISSUE TITLE
Application cannot be launched on OSX Sierra

### ISSUE THREAD

**Issue by Krahulik** [mucommander/mucommander#104] opened 2017-06-13 09:45 UTC
Version 0.9.2 isn't properly signed. OSX 10.12 refuses to launch it with an error '"muCommander" is damaged and can't be opened. You should move it to Trash.'

**Comment by alexey-lysiuk** [comment] 2017-06-13 11:04
Duplicate of #103 I guess.

**Closed** 2017-06-13 11:08 UTC
