### ISSUE TITLE
[Bug] MacOS reports muCommander 1.3.0 as damaged

### ISSUE THREAD

**Issue by d0vgan** [mucommander/mucommander#1005] opened 2023-07-17 06:34 UTC
### Description

When I try to run muCommander 1.3.0 or the latest nightly 1.4.0 under MacOS (Ventura 13.4.1 on Apple M1 Pro), the system reports muCommander is damaged and proposes to move it to Trash.

### Steps to reproduce

I've downloaded the https://github.com/mucommander/mucommander/releases/download/1.3.0-1/mucommander-1.3.0-1.dmg , installed it with replacement, tried to run it - and the MacOS says it is damaged and allows only two options: Move to Trash or Cancel.
The very same situation happens with the latest nightly 1.4.0 (as of today).
I re-downloaded the previous release 1.2.0, installed it with replacement - and it works.
The MacOS is Ventura 13.4.1 on Apple M1 Pro.

### Expected behavior

muCommander 1.3.0 is expected to work under MacOS.

### Actual behavior

muCommander 1.3.0 is reported as damaged by MacOS.

### muCommander version

1.3.0

### Java version

Runtime version: 20
VM name: OpenJDK 64-bit Server VM
VM version: 20+36
VM vendor: Eclipse Adoptium

### Operating System type and version

The MacOS X, 13.4.1 on Apple M1 Pro.

**Comment by pjckoch** [comment] 2023-07-17 09:39
Same for me. Installation via homebrew also leads to the same issue

**Comment by ahadas** [comment] 2023-07-17 09:59
duplicate of #999

**Closed by ahadas** 2023-07-17 09:59 UTC
Labels: bug

**Comment by d0vgan** [comment] 2023-07-17 11:23
Oops, I did not look under the closed issues, assuming this is very new...
For those who, like me, is not good in searching (lol), here is the solution from readme.txt:
```
The application fails to run when installed from a dmg package with the error: "muCommander" is damaged and can't be opened.
On macOS Ventura, grant permission to the Terminal in Settings>Privacy & Security>App Management and run: sudo xattr -cr /Applications/muCommander.app.
On older versions of macOS, run: sudo xattr -dr com.apple.quarantine /Applications/muCommander.app.
```
Note: under MacOS Ventura, first you need to allow Terminal to make changes to the system, then run the `sudo xattr` command for muCommander, and finally allow muCommander to open in the System Settings.

**Comment by neilyoung** [comment] 2023-07-19 06:04
Confirmed. Apple M1 MBP Pro Ventura 13.4.1. DMG installation works, app not loaded because of "damaged.

Suggested fix fails with lots of Operation not permitted. How did you grant terminal system change right? (having strange Windows vibes now...)

**Comment by neilyoung** [comment] 2023-07-19 06:07
Found the security settings. Issue remains. All xattr orders passed now, app refuses to be loaded

**Comment by d0vgan** [comment] 2023-07-19 06:25
> Found the security settings. Issue remains. All xattr orders passed now, app refuses to be loaded

Looks like the final step is left: allow muCommander to open ("Open anyway") in the System Settings, it's under "Privacy & Security".

**Comment by neilyoung** [comment] 2023-07-19 08:39
Yepp, that worked. Thanks

**Comment by Saratxe** [comment] 2023-07-19 18:02
I've still problems on my iMac to open it. I'm using Ventura and followed the steps in the readme.txt but I got:

**option -r not recognized**

back if I enter the sudo xattr command.

**Comment by Saratxe** [comment] 2023-07-19 18:46
No, sudo xattr -cr then I got _option -r not recognized_ back.

**Comment by neilyoung** [comment] 2023-07-19 18:48
```
~ $ sudo xattr --help
Password:
usage: xattr [-l] [-r] [-s] [-v] [-x] file [file ...]
       xattr -p [-l] [-r] [-s] [-v] [-x] attr_name file [file ...]
       xattr -w [-r] [-s] [-x] attr_name attr_value file [file ...]
       xattr -d [-r] [-s] attr_name file [file ...]
       xattr -c [-r] [-s] file [file ...]

The first form lists the names of all xattrs on the given file(s).
The second form (-p) prints the value of the xattr attr_name.
The third form (-w) sets the value of the xattr attr_name to the string attr_value.
The fourth form (-d) deletes the xattr attr_name.
The fifth form (-c) deletes (clears) all xattrs.

options:
  -h: print this help
  -l: print long format (attr_name: attr_value and hex output has offsets and
      ascii representation)
  -r: act recursively
  -s: act on the symbolic link itself rather than what the link points to
  -v: also print filename (automatic with -r and with multiple files)
  -x: attr_value is represented as a hex string for input and output
~ $ 

```

**Comment by neilyoung** [comment] 2023-07-19 18:49
~ $ which xattr
/usr/bin/xattr

**Comment by Saratxe** [comment] 2023-07-19 18:52
Seems, that I've a different version!? How could that be?

usage: xattr [-slz] file [file ...]
       xattr -p [-slz] attr_name file [file ...]
       xattr -w [-sz] attr_name attr_value file [file ...]
       xattr -d [-s] attr_name file [file ...]
       xattr -c [-s] file [file ...]

The first form lists the names of all xattrs on the given file(s).
The second form (-p) prints the value of the xattr attr_name.
The third form (-w) sets the value of the xattr attr_name to attr_value.
The fourth form (-d) deletes the xattr attr_name.
The fifth form (-c) deletes (clears) all xattrs.

options:
  -h: print this help
  -s: act on symbolic links themselves rather than their targets
  -l: print long format (attr_name: attr_value)
  -z: compress or decompress (if compressed) attribute value in zip format

**Comment by Saratxe** [comment] 2023-07-19 19:00
Okay, it's working now! :-)

1. changed my shell from bash to zsh(!!!)
2. enter _sudo xattr -cr /Applications/muCommander.app_
3. allowed muCommander to open ("Open anyway") in the System Settings.
4. That's it.

**Comment by neilyoung** [comment] 2023-07-19 19:01
I'm using bash. From the beginning 😀

**Comment by Saratxe** [comment] 2023-07-19 19:04
If I use bash, then it's not working. With zsh I have also the _xattr -r_ option:

usage: xattr [-l] [-r] [-s] [-v] [-x] file [file ...]
       xattr -p [-l] [-r] [-s] [-v] [-x] attr_name file [file ...]
       xattr -w [-r] [-s] [-x] attr_name attr_value file [file ...]
       xattr -d [-r] [-s] attr_name file [file ...]
       xattr -c [-r] [-s] file [file ...]

The first form lists the names of all xattrs on the given file(s).
The second form (-p) prints the value of the xattr attr_name.
The third form (-w) sets the value of the xattr attr_name to the string attr_value.
The fourth form (-d) deletes the xattr attr_name.
The fifth form (-c) deletes (clears) all xattrs.

options:
  -h: print this help
  -l: print long format (attr_name: attr_value and hex output has offsets and
      ascii representation)
  -r: act recursively
  -s: act on the symbolic link itself rather than what the link points to
  -v: also print filename (automatic with -r and with multiple files)
  -x: attr_value is represented as a hex string for input and output

**Comment by foundryco** [comment] 2023-07-21 20:35
This should sort all of you out rather quickly and rather efficiently:
Open Terminal
Paste: sudo xattr -cr /Applications/muCommander.app
You're welcome
