### ISSUE TITLE
changed code signature in macOS v 1.3.0-1?

### ISSUE THREAD

**Issue by suschizu** [mucommander/mucommander#1002] opened 2023-07-09 15:59 UTC
### Description

I've received a warning that the code signature has changed here since version 1.2.0 and the new code signature is invalid

@ahadas - can you confirm this? thanks!

### Steps to reproduce

codesign -dv --verbose=4 /Path/To/Application.app

### Expected behavior

should contain Arik Hadas (CZHQQ65L42)

### Actual behavior

contains: Eclipse Foundation, Inc. (JCDTMS22B4)

### Screenshots?

<img width="1212" alt="Screenshot 2023-07-09 at 18 04 49" src="https://github.com/mucommander/mucommander/assets/16004333/60e9a40f-c82b-4a4b-98dd-fd886a357c2e">

### muCommander version

1.3.0-1

### Java version

xx

### Operating System type and version

MacOS 13.4

**Comment by ahadas** [comment] 2023-07-09 20:35
@suschizu yeah, that's expected, see https://github.com/mucommander/mucommander/issues/999#issuecomment-1627701479

**Comment by ahadas** [comment] 2023-07-09 20:36
duplicate of #999

**Closed by ahadas** 2023-07-09 20:36 UTC
Labels: bug
