### ISSUE TITLE
Settings that are stored in 'snapshot.xml' are lost

### ISSUE THREAD

**Issue by Andreas0602** [mucommander/mucommander#812] opened 2022-12-23 19:50 UTC
With muCommander build number 43acce2, editor settings and search settings should be persistent, but they aren't. After "playing around" heavily with muCommander for several minutes (performing multiple search operations, viewing multiple files with the built-in viewer, quitting and starting muCommander multiple times, browsing multiple directories), muCommander will forget the settings made by the user and use the default settings instead.

**Comment by ahadas** [comment] 2022-12-23 20:39
@Andreas0602 thanks for trying those features, could you provide any hint on how to reproduce it? it didn't happen to me but it could happen when, e.g., the application fails to start (as the 'snapshot.xml' file is cleared, which is not a bad thing in my opinion because the application is more likely to start well with the default settings)

**Comment by Andreas0602** [comment] 2022-12-23 21:42
I wish I could give in-depth instructions on how to reproduce the issue, but I can't. It just happens from time to time. Starting the application may or may not have something to do with the issue. But I think it's clear that the issue has something to do with the file snapshot.xml. I never lost any settings stored in other configuration files.

I never observed an indication that muCommander failed to start properly. Anyway, I see no point in clearing the editor and search settings in that case, because these settings are not crucial for the startup of the application, as far as I understand. I can't think of any problem that could be solved by clearing the editor and search settings.

In my opinion, muCommander should not silently clear editor and search settings. If muCommander detects a **serious** problem during startup, then muCommander should show a dialog box and ask the user what to do.

**Comment by ahadas** [comment] 2022-12-23 22:05
thanks for the feedback @Andreas0602 
ok, so it's not about the editor/file-search settings not being persistent but rather that settings in the 'snapshot.xml' file are being lost in some cases, however, as we neither have reproduction steps nor logs to investigate this, I'm closing this issue. it doesn't mean that the issue doesn't exist though - if it would happen to me or if you'd be able to provide data we can work with, we'll take a look into that

**Comment by Andreas0602** [comment] 2022-12-24 09:48
I just installed the latest version of muCommander from the nightly build page. After that, my personal search and editor settings were gone. So maybe installing a new muCommander version is one way to increase the probability for the problem to occur.

By the way, I find the closing of this ticket a bit premature. The fact that the problem is difficult to reproduce does not mean that the problem does not exist. It's definitely a real problem. And since we know that muCommander resets 'snapshot.xml' under certain conditions, the way to fix the problem is quite obvious: muCommander should not do that -- at least not silently without asking the user.

**Closed** 2023-02-26 11:28 UTC

**Comment by ahadas** [comment] 2023-03-12 08:16
Version 1.2.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.2.0-1)
