### ISSUE TITLE
Cannot delete files? muCommander 0.9.2 on Windows 10

### ISSUE THREAD

**Issue by philament** [mucommander/mucommander#146] opened 2018-03-07 10:08 UTC
Hi, my install of muCommander 0.9.2. on Windows 10 cannot delete any files. When trying to delete something, the deleting window appears (see below) but stalls at 100%, so the deleting process does not complete. There is no error message or warning. 

![image](https://user-images.githubusercontent.com/31984490/37086287-7a201804-21f7-11e8-8823-03891062b163.png)

Any idea what could cause this and how it might be fixed?

**Comment by xGeorgeV** [comment] 2018-03-09 20:46
You have to use the Parmanent Delete Command intead of Delete Command at v0.9.2, or uncheck the Delete to Trash checkbox.

Modify the shortcuts: Permanent Delete to F8 and Del buttons.

You can use v0.9.0 intead of v0.9.2. The v0.9.0 works fine with Windows 10.

**Comment by xGeorgeV** [comment] 2018-03-12 13:44
Yes, but I do not know its timing.

**Comment by ahadas** [comment] 2018-12-12 11:48
duplicate of #109

**Closed** 2018-12-12 11:49 UTC
