### ISSUE TITLE
0.91rc SFTP not working when I not fill password in connection window

### ISSUE THREAD

**Issue by balucha** [mucommander/mucommander#36] opened 2016-09-09 09:13 UTC
When I fill only IP address, connection working (mucommnader ask for name and password)
When I fill IP address, name and password connection working too.
When I fill IP address and only name, connection not working. Mucommander not ask for password and trying to connect. I must press ESC to cancel trying to connect.  On screen blink  window but I can`t see anything on it.

In old version(0.90) mucommander  ask for password.

Tested on Debian Wheezy 32bit.

**Comment by ahadas** [comment] 2016-09-09 16:14
@balucha , this logic remained as it was in 0.9.0. If only name is specified and password is not specified then we try to connect with empty string as a password.
However, we changed the library used to connect via sftp, could it be that it just takes a bit more time than it used to before showing the 'failure to connect' dialog that asks for a new password?

**Comment by balucha** [comment] 2016-09-12 07:40
On Windows show dialog window and ask for password. On my linux(Debian Wheezy xfce 32.bit) only blink dialog window for very short time.

**Comment by ahadas** [comment] 2016-09-15 10:49
@balucha , I cannot reproduce this issue on debian wheezy xfce.
Please check the following video and let me know if you do something differently:
https://www.youtube.com/watch?v=RGAXdsSl8IU

**Comment by balucha** [comment] 2016-09-16 08:04
No, I do it same way.
I tested connection to different SFTP servers(Debian Wheezy, Opensue 11.0, Debian Jessie) and this problem is only with Debian Jessie SFTP server. I try connect many times, but  dialog windows shows only once(In remaining dialog windows only blink).

**Comment by ahadas** [comment] 2016-09-16 14:32
Is this server publicly available?

**Comment by ahadas** [comment] 2016-10-31 20:26
closing this as I cannot reproduce it. feel free to reopen if it still happens and more information can be provided.

**Closed by ahadas** 2016-10-31 20:26 UTC
