### ISSUE TITLE
Issue when renaming files

### ISSUE THREAD

**Issue by CarlosSousa007** [mucommander/mucommander#268] opened 2020-01-22 05:00 UTC
Thanks for a great product, I have just noticed that occasionally (1 out of 3 or 4 times) there is a problem when trying to rename files on your interface. Its when you click into the text on the filename it seems to not allow you to enter the new name or delete the text. As I say it does not happen all the time but it is quite annoying to swop to finder to rename a file. The interface does not hand as it recovers when clicking elsewhere or escaping.

**Comment by ahadas** [comment] 2020-02-10 13:11
@CarlosSousa007 thanks for reporting this, on what operating system and Java version?

**Comment by CarlosSousa007** [comment] 2020-02-10 15:23
Version information

muCommander
Version: 0.9.3
Build date: 2019/05/13
Build number: df79168

Java
Runtime version: 1.8.0_161
VM name: Java HotSpot(TM) 64-Bit Server VM
VM version: 25.161-b12
VM vendor: Oracle Corporation

OS
Name: Mac OS X
Version: 10.15.3
Architecture: x86_64

Locale
Language: en
Country: ZA
Encoding: UTF-8

**Comment by arazinger** [comment] 2020-04-14 08:04
I'm having this kind of issues all the time...for a couple of years now. After doing some action like rename, copy, delete, the UI becomes unresponsive. Switching to another app and back again helps, but it's annoying.

I was trying to track this problem down a while ago and as I remember it could have something to do with legacy Java SE 6 runtime (https://support.apple.com/kb/DL1572?locale=sl_SI)...not 100% sure.

Maybe it helps.
Great work anyway!

**Comment by ahadas** [comment] 2022-06-05 15:07
I can't reproduce that with the latest version (1.0.0), it might have been resolved already when Java was upgraded.. so I'm closing but please reopen if you still face this

**Closed by ahadas** 2022-06-05 15:07 UTC
