### ISSUE TITLE
Language support in the list

### ISSUE THREAD

**Issue by oulim78** [mucommander/mucommander#552] opened 2022-01-12 16:57 UTC
I am a user of mucommander-0.9.7-1-portable version in South Korea.
In Windows, there is a limit on the port number of the samba server, so I have recognized this program and am using it well.
Korean language support is good.
However, Korean is well supported in the menu, but all Korean is broken in the list.
There is no part about language support in the list in the Preferences.

![screenshot2](https://user-images.githubusercontent.com/17499025/149185768-55baae57-5f9c-405f-a79b-34b285e05990.png)

**Comment by ahadas** [comment] 2022-01-12 17:34
@oulim78 in this screenshot the menu is in English, does it work well on this machine when changing the language to Korean?

**Comment by oulim78** [comment] 2022-01-14 11:46
Even if I change the language setting in the menu part, Korean does not appear normally in the list. In the settings, only the language setting in the menu part can be changed. Is there any way to make it appear properly in Korean in the list?

**File>Preferences>General>Language ... Korean**
![menu_korean](https://user-images.githubusercontent.com/17499025/149510213-29280066-4c3f-4a4f-a310-6ba7c5b5268b.png)


**File>Preferences>General>Language ... English**
![menu_english](https://user-images.githubusercontent.com/17499025/149510216-220c73ff-577a-4dcb-ac20-28add0c9b667.png)


In both cases, Korean is not displayed normally in the list.

**Comment by ahadas** [comment] 2022-05-22 16:07
@oulim78 this means that the problem is with the font that is used within the file table and therefore I'm closing this issue. I'd recommend to try different fonts in `File -> Preferences -> Appearance -> Themes -> Edit... -> Folder pane -> General -> Font`

**Closed by ahadas** 2022-05-22 16:07 UTC
