### ISSUE TITLE
muCommander asks *every time* for permission to accept incoming network connections 

### ISSUE THREAD

**Issue by rhstanton** [mucommander/mucommander#322] opened 2020-04-14 17:14 UTC
After just updating to 0.9.4-2 on my Mac (OSX Catalina), every time I start muCommander I'm asked if I want to grant permission for muCommander to accept incoming network connections. I always say yes, and everything works fine, but it just asks again next time I start the program.

**Comment by ahadas** [comment] 2020-04-14 21:16
This probably relates to the other issue you've opened. I didn't notice this one though. it would be difficult to investigate this without being able to reproduce it. Could you try do disable 'check for updates on startup' maybe? or upload a screenshot/recording of this?

**Comment by ahadas** [comment] 2020-04-16 21:16
@rhstanton , could you please share the log of one of startups in which you get the dialog and a copy of your `preferences.xml` file (can be found on `~/Library/Preferences/muCommander`)

**Comment by rhstanton** [comment] 2020-04-16 23:25
With pleasure, but what startup log are you asking for...?

**Comment by rhstanton** [comment] 2020-04-17 02:42
Turning off check for updates doesn't seem to help. Here's my preferences.xml:

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<preferences>
    <display_compact_file_size>false</display_compact_file_size>
    <time_format>hh:mm a</time_format>
    <quit_confirmation>false</quit_confirmation>
    <lookAndFeel>com.apple.laf.AquaLookAndFeel</lookAndFeel>
    <show_splash_screen>true</show_splash_screen>
    <preferred_encodings>UTF-8,UTF-16,ISO-8859-1,windows-1252,KOI8-R,Big5,GB18030,EUC-KR,Shift_JIS,ISO-2022-JP,EUC-JP</preferred_encodings>
    <check_for_updates_on_startup>false</check_for_updates_on_startup>
    <date_format>MM/dd/yy</date_format>
    <language>en</language>
    <enable_system_notifications>true</enable_system_notifications>
    <date_separator>/</date_separator>
    <macosx>
        <brushed_metal_look>false</brushed_metal_look>
        <screen_menu_bar>true</screen_menu_bar>
    </macosx>
    <auto_refresh>
        <wait_after_refresh>10000</wait_after_refresh>
        <check_period>3000</check_period>
    </auto_refresh>
    <ftp>
        <list_hidden_files>false</list_hidden_files>
    </ftp>
    <mail>
        <smtp_port>25</smtp_port>
    </mail>
    <log>
        <level>WARNING</level>
        <buffer_size>200</buffer_size>
    </log>
    <smb>
        <use_extended_security>false</use_extended_security>
        <lm_compatibility>0</lm_compatibility>
    </smb>
    <status_bar>
        <visible>true</visible>
    </status_bar>
    <bonjour>
        <discovery_enabled>true</discovery_enabled>
    </bonjour>
    <toolbar>
        <icon_scale>1.0</icon_scale>
        <visible>true</visible>
    </toolbar>
    <progress_dialog>
        <expanded>true</expanded>
        <close_when_finished>true</close_when_finished>
    </progress_dialog>
    <command_bar>
        <icon_scale>1.0</icon_scale>
        <visible>true</visible>
    </command_bar>
    <shell>
        <history_size>100</history_size>
        <use_custom>false</use_custom>
        <encoding>UTF-8</encoding>
        <autodect_encoding>false</autodect_encoding>
    </shell>
    <startup_folder>
        <on_startup>lastFolders</on_startup>
        <custom_folders>
            <left>/Users/stanton</left>
            <right>/Users/stanton</right>
        </custom_folders>
    </startup_folder>
    <theme>
        <path>ClassicCommander</path>
        <type>predefined</type>
    </theme>
    <file_table>
        <icon_scale>1.0</icon_scale>
        <show_single_tab_header>false</show_single_tab_header>
        <cd_follows_symlinks>false</cd_follows_symlinks>
        <show_system_folders>true</show_system_folders>
        <use_system_file_icons>applications</use_system_file_icons>
        <show_hidden_files>true</show_hidden_files>
        <show_ds_store_files>true</show_ds_store_files>
        <auto_size_columns>true</auto_size_columns>
        <show_folders_first>true</show_folders_first>
    </file_table>
</preferences>

**Comment by ahadas** [comment] 2020-04-17 07:26
Thanks. Could you please share it as an xml so I could also see the keys (in this key-value(s) structure)? You can drop personal things like local paths. I just want to see if there's a difference between the configuration you use and mine that might point us to the cause of this issue.
Let's start with that and see if the log is still needed.

**Comment by rhstanton** [comment] 2020-04-17 16:30
I just copied and pasted the text from the xml file. It looked fine when I pasted it in, but not so fine when I sent it off! How can I preserve the original format?

**Comment by ahadas** [comment] 2020-04-17 19:17
Oh, add a line with \`\`\`xml before the xml content and a line with ``` afterward.

**Comment by rhstanton** [comment] 2020-04-17 20:33
Here you are:

```xml 

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<preferences>
    <display_compact_file_size>false</display_compact_file_size>
    <time_format>hh:mm a</time_format>
    <quit_confirmation>false</quit_confirmation>
    <lookAndFeel>com.apple.laf.AquaLookAndFeel</lookAndFeel>
    <show_splash_screen>true</show_splash_screen>
    <preferred_encodings>UTF-8,UTF-16,ISO-8859-1,windows-1252,KOI8-R,Big5,GB18030,EUC-KR,Shift_JIS,ISO-2022-JP,EUC-JP</preferred_encodings>
    <check_for_updates_on_startup>false</check_for_updates_on_startup>
    <date_format>MM/dd/yy</date_format>
    <language>en</language>
    <enable_system_notifications>true</enable_system_notifications>
    <date_separator>/</date_separator>
    <macosx>
        <brushed_metal_look>false</brushed_metal_look>
        <screen_menu_bar>true</screen_menu_bar>
    </macosx>
    <auto_refresh>
        <wait_after_refresh>10000</wait_after_refresh>
        <check_period>3000</check_period>
    </auto_refresh>
    <ftp>
        <list_hidden_files>false</list_hidden_files>
    </ftp>
    <mail>
        <smtp_port>25</smtp_port>
    </mail>
    <log>
        <level>WARNING</level>
        <buffer_size>200</buffer_size>
    </log>
    <smb>
        <use_extended_security>false</use_extended_security>
        <lm_compatibility>0</lm_compatibility>
    </smb>
    <status_bar>
        <visible>true</visible>
    </status_bar>
    <bonjour>
        <discovery_enabled>true</discovery_enabled>
    </bonjour>
    <toolbar>
        <icon_scale>1.0</icon_scale>
        <visible>true</visible>
    </toolbar>
    <progress_dialog>
        <expanded>true</expanded>
        <close_when_finished>true</close_when_finished>
    </progress_dialog>
    <command_bar>
        <icon_scale>1.0</icon_scale>
        <visible>true</visible>
    </command_bar>
    <shell>
        <history_size>100</history_size>
        <use_custom>false</use_custom>
        <encoding>UTF-8</encoding>
        <autodect_encoding>false</autodect_encoding>
    </shell>
    <startup_folder>
        <on_startup>lastFolders</on_startup>
        <custom_folders>
            <left>/Users/stanton</left>
            <right>/Users/stanton</right>
        </custom_folders>
    </startup_folder>
    <theme>
        <path>ClassicCommander</path>
        <type>predefined</type>
    </theme>
    <file_table>
        <icon_scale>1.0</icon_scale>
        <show_single_tab_header>false</show_single_tab_header>
        <cd_follows_symlinks>false</cd_follows_symlinks>
        <show_system_folders>true</show_system_folders>
        <use_system_file_icons>applications</use_system_file_icons>
        <show_hidden_files>true</show_hidden_files>
        <show_ds_store_files>true</show_ds_store_files>
        <auto_size_columns>true</auto_size_columns>
        <show_folders_first>true</show_folders_first>
    </file_table>
</preferences>

```

**Comment by ahadas** [comment] 2020-04-18 09:53
Ok, I've managed to reproduce it on my machine - it seems related to the discovery of Bonjour services. Could you please try to disable it (via Preferences->Misc page) and tell if it still happens?

**Comment by rhstanton** [comment] 2020-04-19 00:50
Yes, that solves the problem. Turning Bonjour back on brings the problem back.

**Comment by ahadas** [comment] 2020-04-20 14:50
Yeah, seems it is [a known issue for quite some time](https://github.com/mucommander/mucommander/blob/master/package/readme.txt#L55-L56).

**Comment by ahadas** [comment] 2022-06-05 14:27
Duplicate of #129

**Closed** 2022-06-05 14:46 UTC
