### ISSUE TITLE
Running under OpenBSD 6.7

### ISSUE THREAD

**Issue by j4n3b** [mucommander/mucommander#342] opened 2020-05-18 03:33 UTC
on OpenBSD 6.7-64bit with `/usr/local/jdk-1.8.0` which is OpenJDK 1.8 I get this:
Do you have nay solution for it?

[Complete  Error >> Look at it Please >>](https://openports.se/devel/py-gobject3)

```
   ____  _____ _______             _____    ________    ____
  / __ \/ ___// ____(_)___ _____ _/ ___/   / ____/ /   /  _/
 / / / /\__ \/ / __/ / __ `/ __ `/\__ \   / /   / /    / /  
/ /_/ /___/ / /_/ / / /_/ / /_/ /___/ /  / /___/ /____/ /   
\____//____/\____/_/\__,_/\__,_//____/   \____/_____/___/   

:: https://github.com/renatoathaydes/osgiaas ::

>> ERROR: Bundle mucommander-core [86] Error starting file:/home/admin/Downloads/mu/app/mucommander-core-0.9.4.jar (org.osgi.framework.BundleException: Unable to resolve mucommander-core [86](R 86.0): missing requirement [mucommander-core [86](R 86.0)] osgi.wiring.package; (&(osgi.wiring.package=com.mucommander.commons.file.archive)(version>=0.9.0)(!(version>=1.0.0))) [caused by: Unable to resolve mucommander-commons-file [42](R 42.0): missing requirement [mucommander-commons-file [42](R 42.0)] osgi.wiring.package; (&(osgi.wiring.package=com.mucommander.commons.util)(version>=0.9.0)(!(version>=1.0.0))) [caused by: Unable to resolve mucommander-commons-util [45](R 45.0): missing requirement [mucommander-commons-util [45](R 45.0)] osgi.ee; (&(osgi.ee=JavaSE)(version=11))]] Unresolved requirements: [[mucommander-core [86](R 86.0)] osgi.wiring.package; (&(osgi.wiring.package=com.mucommander.commons.file.archive)(version>=0.9.0)(!(version>=1.0.0)))])
org.osgi.framework.BundleException: Unable to resolve mucommander-core [86](R 86.0): missing requirement [mucommander-core [86](R 86.0)] osgi.wiring.package; (&(osgi.wiring.package=com.mucommander.commons.file.archive)(version>=0.9.0)(!(version>=1.0.0))) [caused by: Unable to resolve mucommander-commons-file [42](R 42.0): missing requirement [mucommander-commons-file [42](R 42.0)] osgi.wiring.package; (&(osgi.wiring.package=com.mucommander.commons.util)(version>=0.9.0)(!(version>=1.0.0))) [caused by: Unable to resolve mucommander-commons-util [45](R 45.0): missing requirement [mucommander-commons-util [45](R 45.0)] osgi.ee; (&(osgi.ee=JavaSE)(version=11))]] Unresolved requirements: [[mucommander-core [86](R 86.0)] osgi.wiring.package; (&(osgi.wiring.package=com.mucommander.commons.file.archive)(version>=0.9.0)(!(version>=1.0.0)))]
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4368)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2281)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1539)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
```

**Comment by ahadas** [comment] 2020-05-18 06:47
Hi @j4n3b , thanks for reporting this. It seems like a duplicate of #295 - the upcoming release, 0.9.5, will work again with Java 8 (on Linux).
Closing but feel free to reopen if needed.

**Closed by ahadas** 2020-05-18 06:47 UTC
