### ISSUE TITLE
Current file selection is not moving upon pressing Up/Down buttons

### ISSUE THREAD

**Issue by abcdenis** [mucommander/mucommander#44] opened 2016-10-27 13:30 UTC
Hi,
just installed 0.9.1.
Found out that selection line stay on same file when I am pressing Up/Down buttons on keyboard.
Suddenly selection bar moved when I switched to another application and then back!
Looks like someone forgot to call redraw function.

I rollback to 0.9.0 and switched off new version check.

**Comment by ahadas** [comment] 2016-10-27 14:32
Hi, on which type and version of operating system did you experience that?

**Comment by abcdenis** [comment] 2016-10-27 18:25
OSX ElCapitan 10.11.6

**Comment by ahadas** [comment] 2016-10-27 19:09
ok, and what version of Java do you use?

**Comment by ahadas** [comment] 2016-10-27 20:36
since keyboard's handling seems to work fine on several machines I tested on including my MacBook Pro with OS X El Capitan and on another user's machine (it was also installed with El Capitan IIRC), I will not be able to do much about it without any log or exact reproduction steps..
The more information you provide, the easier it will be to try to identify why it happens on your machine - do you use it in a virtual machine maybe? any non-standard keyboard?

**Comment by abcdenis** [comment] 2016-10-28 00:53
﻿﻿~ java -version
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)

Macbook Pro, external PC keyboard. But after downgrade everything works fine.

Also there is some status line with info on curent file/selection. It was changing on pressing Up/Down keys so some part of program knows about moving current file cursor.

**Comment by ahadas** [comment] 2016-10-28 16:23
ok, the fact that the current selection in the status bar is updated means that you're probably right about that being a rendering issue. can you please tell how did you install muCommander (from which installation file) and whether it works ok when you change the selection using the mouse?

**Comment by ahadas** [comment] 2016-11-03 22:47
Closing since I cannot reproduce the issue with the given information.
Feel free to reopen if more information can be provided about the problem or how can it be reproduced.

**Closed by ahadas** 2016-11-03 22:47 UTC
