### ISSUE TITLE
[Bug] crash on open ventura

### ISSUE THREAD

**Issue by zorflieg** [mucommander/mucommander#1027] opened 2023-08-04 23:58 UTC
### Description

On apple silicon M1 i downloaded the new 1.3.0 version and overwrote the old to upgrade.  Both java and non java osx crashes on open for me with the

### Steps to reproduce

upgrade / overwrite from 1.2-2 and open.

### Expected behavior

to open.

### Actual behavior

it reports as damaged..

### Screenshots?

![Screenshot 2023-08-05 at 9 54 35 am](https://github.com/mucommander/mucommander/assets/64879056/835bd954-dc32-482a-83b9-244b97c56160)

### muCommander version

1.3.0

### Java version

0.9.1

### Operating System type and version

ventura 13.5

**Comment by ahadas** [comment] 2023-08-05 08:43
Duplicate of #999

**Closed by ahadas** 2023-08-05 08:43 UTC
Labels: bug
