### ISSUE TITLE
User, not a programmer, Update crashes program

### ISSUE THREAD

**Issue by silverlox** [mucommander/mucommander#103] opened 2017-06-10 22:22 UTC
I had a working program with Mucommander v0.9.1 and was advised an update was available. 
The update replaced the working program.
I now don't have a working copy as nothing I do will restore the program back to working. 
Would appreciate some help on this please.

I have re-installed Java, its up to date but every time I install 0.9.1 or 0.9.2 I'm informed the program is corrupt and should be deleted.
What am I doing wrong?

**Comment by hickey221** [comment] 2017-06-12 16:04
I have the same issue on OSX 10.10.5, having installed from the .dmg. Says the file is damaged and cannot be run.

In the mean time I was able to run the program by using the .jar file inside the **portable version**, which you can download from the same page as the other packages. That might work for you too.

**Comment by silverlox** [comment] 2017-06-12 18:03
I did try that and it did work but I cannot even get the original .9.1 to install and work again.
It was fine on 0.9.1 - wish I had never tried to upgrade.

**Comment by alexey-lysiuk** [comment] 2017-06-12 19:19
If it's about running muCommander on macOS then run `Terminal.app` and execute the following:
```
curl -LO https://github.com/mucommander/mucommander/releases/download/0.9.2/mucommander-0.9.2.dmg
open mucommander-0.9.2.dmg
```
This will download 0.9.2 from GitHub's Releases page and will open the disk image.

Alternatively, if you are dead set against downloading something via `curl` and want to download in your web browser no matter what then execute the following command in `Terminal.app`:
```
xattr -d com.apple.quarantine ~/Downloads/mucommander-0.9.2.dmg
```
You should do this after downloading but before opening the disk image. Also, the command assumes that `mucommander-0.9.2.dmg` was saved in `Downloads` folder.

**Comment by ahadas** [comment] 2017-06-13 18:49
Seems like a duplicate of #64 .
Feel free to reopen if that's a different issue.

**Closed by ahadas** 2017-06-13 18:49 UTC

**Comment by silverlox** [comment] 2017-06-13 19:22
Hello 

The first command, using curl did not work for me, however the second version of the install worked fine.

I’m a bit confused why one worked but the other did not. 

Thanks for the assistance.

Kind regards
Mike Steddy

**Comment by silverlox** [comment] 2017-06-13 19:25
Looked at the thread for #64 - It seems that every update causes problems. Why should we need to disable gatekeeper to install/run this program?

**Comment by ahadas** [comment] 2017-06-13 20:19
@silverlox That's true. We were thinking about signing the application properly for Mac OS in the past (when gatekeeper appeared in ~10.7) but never get to it. IIRC, it required both some time to work on it and some money (to acquire Apple's developer certificate)..
