### ISSUE TITLE
Damaged app in mucommander-0.9.1-apple-java.dmg

### ISSUE THREAD

**Issue by Jimsy2** [mucommander/mucommander#81] opened 2017-03-15 09:35 UTC
Trying to launch muCommander program from the .dmg-image mentioned in the title gives me a pop-up saying

>   **"muCommander" is damaged and can't be**
>   **opened. You should move it to Trash.**

When trying to open muCommander from the `mucommander-0.9.1.dmg`
instead I get a "JRELoadError", even though first time launch of `mucommander-0.9.1-apple-java.dmg` had already installed Java.

Running `mucommander.jar` from the `mucommander-0.9.1-portable.tar.gz` works fine though - only a generic icon is used instead of the ghost app-icon.

**Comment by zlobjc** [comment] 2017-03-31 09:57
me be duplicate of [issues](https://github.com/mucommander/mucommander/issues/64)

**Comment by ahadas** [comment] 2017-04-21 16:22
seems like a duplicate of #64 indeed
@Jimsy2  feel free to reopen if it is a different issue

**Closed by ahadas** 2017-04-21 16:22 UTC

**Comment by stefek99** [comment] 2017-12-19 11:11
![image](https://user-images.githubusercontent.com/249703/34154426-c434a1a0-e4b5-11e7-9c45-b7dd649215f4.png)


How to run the portable `.jar`?
